# coding: utf-8
from datetime import datetime
from snowballing.models import *
from ..places import *

agostinelli2019a = DB(Work(
    2019, "Achieving GDPR compliance of BPMN process models",
    due="Unrelated to provenance",
    display="agostinelli",
    authors="Agostinelli, Simone and Maggi, Fabrizio Maria and Marrella, Andrea and Sapio, Francesco",
    place=CAiSE,
    ID='agostinelli2019achieving',
    category='unrelated',
    cluster_id='6779454441181988618',
    entrytype='inproceedings',
    link='http://www.diag.uniroma1.it/~marrella/papers/CAiSE_Forum_2019.pdf',
    organization='Springer',
    pp='10--22',
    scholar='https://scholar.google.com/scholar?cites=6779454441181988618&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='CseYKeV1FV4J',
    scholar_ok=True,
    forward_steps=1,
))

araujo2019a = DB(Work(
    2019, "A utilizacao de dados pessoais sensiveis na formacao do perfil comportamental de pessoas naturais e o potencial dano aos seus titulares",
    due="Unrelated to provenance",
    display="araujo",
    authors="Araujo, Priscila Maria Menezes de",
    place=Thesis,
    ID='araujo2019utilizaccao',
    category='unrelated',
    cluster_id='14057884673132835334',
    entrytype='article',
    link='https://bdm.unb.br/bitstream/10483/25207/1/2019_PriscilaMariaMenezesDeAraujo_tcc.pdf',
    scholar='https://scholar.google.com.br/scholar?cites=14057884673132835334&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='BrJ926CjF8MJ',
    scholar_ok=True,
    forward_steps=1,
))

bartolini2019a = DB(Work(
    2019, "Enhancing Business Process Modelling with Data Protection Compliance: An Ontology-based Proposal.",
    due="The paper does not introduce a model or an ontology. This contribution extends BPMN with the concepts expressed in the PrOnto ontology and provide a support to evaluate compliance through a structured approach to verify the GDPR requirements implementation and detect potential violations.",
    display="bartolini",
    authors="Bartolini, Cesare and Calabró, Antonello and Marchetti, Eda",
    place=Web,
    ID='bartolini2019enhancing',
    category='unrelated',
    cluster_id='631927206051589866',
    entrytype='inproceedings',
    link='https://www.scitepress.org/Papers/2019/73923/73923.pdf',
    pp='421--428',
    scholar='https://scholar.google.com.br/scholar?cites=631927206051589866&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='6i6cIHIOxQgJ',
    scholar_ok=True,
    summary='"The research and industrial environments are struggling to identify practical approaches to highlight the (new) duties of controllers of personal data and foster the transition of IT-based systems, services, and tools to comply with the GDPR. In this paper, we present a solution for enhancing the modelling of business processes with facilities to help evaluate the compliance with the GDPR. The proposal is based on a model describing the constituents of the data protection domain: a structured form of the legal text, an ontology of data protection concepts, and a machine-readable translation of the GDPR provisions. An example of application is also provided."',
    start_set=True,
))

besik2019a = DB(Work(
    2019, "Ontology-Based Privacy Compliance Checking for Clinical Workflows.",
    due="This paper has proposed a compliance-check architecture based on Java technologies. This system was built under three ontologies: the first proposes terms for the privacy layer, suggesting classes to GDPR (in particular, purpose specifications, data minimization, processing compliant-checking, and limit of retention period), privacy policies, and privacy preferences (when the data subjects to determine who can access their data and for what purposes). To represent the activities, this approach has inherited Business Process Model and Notation (BPMN). Finally, the last ontology contains terms of the specific clinical domain.\n\nThe authors demonstrate that this approach can check compliance through the ministration of a Java-based open source business rule management system. They show the usability of this approach in the running process, which also illustrates how these three ontologies should work together.\n\nAlthough the compliance checker was built over a specific technology (that we probably will not utilize), we have considered the privacy ontology can contribute to the objective of our study. Indeed, this privacy ontology provides concepts to represent privacy policy constraints. Such information is required to answer the obligations we have aimed to achieve.\n\nIn face of this, we have included this article to see whether the proposed model was extended to meet further obligations.",
    display="besik",
    authors="Besik, Saliha Irem and Freytag, Johann-Christoph",
    place=LWDA,
    ID='besik2019ontology',
    category='ok',
    cluster_id='9953792441592462448',
    entrytype='inproceedings',
    link='https://www.researchgate.net/profile/Saliha-Besik/publication/336129066_Ontology-Based_Privacy_Compliance_Checking_for_Clinical_Workflows/links/5d90d2cb299bf10cff1a003e/Ontology-Based-Privacy-Compliance-Checking-for-Clinical-Workflows.pdf',
    pp='218--229',
    scholar='https://scholar.google.com.br/scholar?cites=9953792441592462448&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='cDwW-Xz5IooJ',
    scholar_ok=True,
    start_set=True,
    useful=True,
    not_directly_related_to_provenance=True,
))

# buyle2019a = DB(Work(
#     2019, "Streamlining governmental processes by putting citizens in control of their personal data",
#     due="[toReview=True; Forward=1; Page=1]",
#     display="buyle",
#     authors="Buyle, Raf and Taelman, Ruben and Mostaert, Katrien and Joris, Geroen and Mannens, Erik and Verborgh, Ruben and Berners-Lee, Tim",
#     place=arXiv,
#     ID='buyle2019streamlining',
#     category='unrelated',
#     cluster_id='12412400709025252009',
#     entrytype='inproceedings',
#     link='https://biblio.ugent.be/publication/8644983/file/8655877',
#     organization='Springer',
#     pp='346--359',
#     scholar='https://scholar.google.com.br/scholar?cites=12412400709025252009&as_sdt=2005&sciodt=0,5&hl=en',
#     scholar_id='qcJBX660QawJ',
#     scholar_ok=True,
# ))


blanco2019a = DB(Work(
    2019, "Using an enterprise architecture model for GDPR compliance principles",
    due="Unrelated to provenance",
    display="blanco",
    authors="Blanco-Lainé, Gaëlle and Sottet, Jean-Sébastien and Dupuy-Chessa, Sophie",
    place=IFIP,
    ID='blanco2019using',
    category='unrelated',
    cluster_id='16601134074334111014',
    entrytype='inproceedings',
    link='https://hal.archives-ouvertes.fr/hal-02482761/document',
    organization='Springer',
    pp='199--214',
    scholar='https://scholar.google.com/scholar?cites=16601134074334111014&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='JmVR6XsTY-YJ',
    scholar_ok=True,
    forward_steps=1,
))

bonatti2019a = DB(Work(
    2019, "A Richer Policy Language for GDPR Compliance.",
    due="This document focuses in how the SPECIAL policy language, the related approach, can be performed. This document provides the algorithms implemented in semantic reasoners and demonstrate the feasibility of such approach in acheive compliance. Thus, this document is out of our purposes with this literature review.",
    display="bonatti",
    authors="Bonatti, Piero A and Petrova, Iliana M and Sauro, Luigi",
    place=UnknownConference,
    ID='bonatti2019richer',
    category='unrelated',
    cluster_id='7500614371801874310',
    entrytype='inproceedings',
    link='http://ceur-ws.org/Vol-2373/paper-5.pdf',
    scholar='https://scholar.google.com/scholar?cites=7500614371801874310&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='hr9w_AeJF2gJ',
    scholar_ok=True,
    backward_steps=1,
))

buyle2019a = DB(Work(
    2019, "Streamlining governmental processes by putting citizens in control of their personal data",
    due="Unrelated to provenance",
    display="buyle",
    authors="Buyle, Raf and Taelman, Ruben and Mostaert, Katrien and Joris, Geroen and Mannens, Erik and Verborgh, Ruben and Berners-Lee, Tim",
    place=EGOSE,
    ID='buyle2019streamlining',
    category='unrelated',
    cluster_id='12412400709025252009',
    entrytype='inproceedings',
    link='https://biblio.ugent.be/publication/8644983/file/8655877',
    organization='Springer',
    pp='346--359',
    scholar='https://scholar.google.com.br/scholar?cites=12412400709025252009&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='qcJBX660QawJ',
    scholar_ok=True,
    forward_steps=1,
))

coleti2019a = DB(Work(
    2019, "Design patterns to support personal data transparency visualization in mobile applications",
    due="Unrelated to provenance",
    display="coleti",
    authors="Coleti, Thiago Adriano and Morandini, Marcelo and Vilela Leite Filgueiras, Lucia and Pizzigatti Correa, Pedro Luiz and Oliveira, Igor Goulart de and Barbosa, Cinthyan Renata Sachs Camerlengo de",
    place=HCII,
    ID='coleti2019design',
    category='unrelated',
    cluster_id='4772385166119998855',
    entrytype='inproceedings',
    link='https://www.researchgate.net/profile/Thiago-Coleti/publication/334365180_Design_Patterns_to_Support_Personal_Data_Transparency_Visualization_in_Mobile_Applications/links/61f2b44f5779d35951da69ab/Design-Patterns-to-Support-Personal-Data-Transparency-Visualization-in-Mobile-Applications.pdf',
    organization='Springer',
    pp='46--62',
    scholar='https://scholar.google.com/scholar?cites=4772385166119998855&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='hxXt_QXrOkIJ',
    scholar_ok=True,
    backward_steps=1,
))

corrales2019a = DB(Work(
    2019, "Legal Tech, Smart Contracts and Blockchain",
    due="Unrelated to provenance",
    display="corrales",
    authors="Corrales, Marcelo and Fenwick, Mark and Haapio, Helena",
    place=Book,
    ID='corrales2019legal',
    category='unrelated',
    cluster_id='2363148849750536611',
    entrytype='book',
    link='https://link.springer.com/content/pdf/10.1007/978-981-13-6086-2.pdf',
    organization='Springer',
    scholar='https://scholar.google.com/scholar?cites=2363148849750536611&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='o_HAvFuXyyAJ',
    scholar_ok=True,
    backward_steps=1,
))

curia2019a = DB(Work(
    2019, "CURIA - Documents",
    due="This document is an opinion of the advocate genral, not a scientific paper",
    display="curia",
    authors="CURIA",
    place=Web,
    ID='CURIADoc43:online',
    category='unrelated',
    entrytype='misc',
    scholar_ok='@misc{CURIADoc43:online,\nauthor = {CURIA},\ntitle = {CURIA - Documents},\nhowpublished = {https://curia.europa.eu/juris/document/document.jsf?docid=212023&mode=req&pageIndex=1&dir=&occ=first&part=1&text=&doclang=EN&cid=5704393},\nyear = {2019},\nnote = {(Accessed on 06/13/2022)}\n}',
    backward_steps=1,
))

davari2019a = DB(Work(
    2019, "Access control model extensions to support data privacy protection based on GDPR",
    due="File not available",
    display="davari",
    authors="Davari, Maryam and Bertino, Elisa",
    place=IEEEBD,
    ID='davari2019access',
    category='nofile',
    cluster_id='12118505575534909018',
    entrytype='inproceedings',
    link='https://ieeexplore.ieee.org/abstract/document/9006455/',
    organization='IEEE',
    pp='4017--4024',
    scholar='https://scholar.google.com.br/scholar?cites=12118505575534909018&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='WlZZRp2ULagJ',
    scholar_ok=True,
    backward_steps=1,
))

debruyne2019a = DB(Work(
    2019, "Towards generating policy-compliant datasets",
    display="debruyne",
    due="The proposed ontology seems not fully publicly available.",
    authors="Debruyne, Christophe and Pandit, Harshvardhan J and Lewis, Dave and O'Sullivan, Declan",
    place=IEEEICSC,
    ID='debruyne2019towards',
    category='unrelated',
    cluster_id='6348710661205469160',
    entrytype='inproceedings',
    link='https://www.academia.edu/download/62422050/2019-icsc-preprint20200320-112486-1pitqhq.pdf',
    organization='IEEE',
    pp='199--203',
    scholar='https://scholar.google.com/scholar?cites=6348710661205469160&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='6CfjnrUmG1gJ',
    scholar_ok=True,
    useful=True,
    not_directly_related_to_provenance=True,
    backward_steps=1,
))

debruyne2019b = DB(Work(
    2019, "An Ontology for Representing and Annotating Data Flows to Facilitate Compliance Verification",
    due="This approach has no direct relation to provenance. This one meets the GDPR by proposing a tiny Data Flow Diagrams ontology, which is a data-oriented model. The author argues that provenance approaches are workflow-oriented and, in general, are focused on 'a posterior' representation. The ontology is available at https://w3id.org/dfd. The approach also utilizes prior ontologies to demonstrate that the model can facilitate the compliance verification.",
    display="debruyne",
    authors="Debruyne, Christophe and Riggio, Jonathan and De Troyer, Olga and O’Sullivan, Declan",
    place=RuleML,
    ID='debruyne2019ontology',
    category='unrelated',
    cluster_id='14391272085701969421',
    entrytype='inproceedings',
    link='https://chrdebru.github.io/papers/2019-rcis-preprint.pdf',
    organization='IEEE',
    pp='1--6',
    scholar='https://scholar.google.com/scholar?cites=14391272085701969421&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='DcZCtrYRuMcJ',
    scholar_ok=True,
    backward_steps=1,
))

drozd2019a = DB(Work(
    2019, "Consent Comprehension Made Easy Demo",
    due="Unrelated to provenance",
    display="drozd",
    authors="Drozd, Olha and Kirrane, Sabrina",
    place=PETS,
    ID='drozd2019consent',
    category='unrelated',
    cluster_id='9296820521000158942',
    entrytype='inproceedings',
    link='https://penni.wu.ac.at/papers/PUT%202019%20Consent%20Comprehension%20Made%20Easy%20Demo.pdf',
    pp='1',
    scholar='https://scholar.google.com/scholar?cites=9296820521000158942&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='3sbG1gHxBIEJ',
    scholar_ok=True,
    backward_steps=1,
))

drozd2019b = DB(Work(
    2019, "I agree: Customize your personal data processing with the core user interface",
    due="Unrelated to provenance",
    display="drozd",
    authors="Drozd, Olha and Kirrane, Sabrina",
    place=TrustBus,
    ID='drozd2019agree',
    category='unrelated',
    cluster_id='6476706615843169766',
    entrytype='inproceedings',
    link='https://epub.wu.ac.at/7916/1/Trustbus%202019%20I%20Agree%20Customize%20your%20Personal%20Data%20Processing%20with%20the%20CoRe%20User%20Interface.pdf',
    organization='Springer',
    pp='17--32',
    scholar='https://scholar.google.com/scholar?cites=6476706615843169766&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='5iXBH1ri4VkJ',
    scholar_ok=True,
    backward_steps=1,
))

fernández2019a = DB(Work(
    2019, "Privacy-aware linked widgets",
    due="FIle not publicly available",
    display="fernández",
    authors="D. Fernández, Javier and J. Ekaputra, Fajar and Ruswono Aryan, Peb and Azzam, Amr and Kiesling, Elmar",
    place=WWW,
    ID='d2019privacy',
    category='nofile',
    cluster_id='4943330782496666802',
    entrytype='inproceedings',
    link='https://dl.acm.org/doi/pdf/10.1145/3308560.3317591?casa_token=S99wGcfREuIAAAAA:HXsUnB1LZSnwBCbicOTIjAFoxCXPdcafvMMv1gjkq0lDIXYAENS0fVjvUDYjbraxm-_4h6P2wxo1Xg',
    pp='508--514',
    scholar='https://scholar.google.com.br/scholar?cites=4943330782496666802&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='srT34Sc9mkQJ',
    scholar_ok=True,
    forward_steps=1,
))

fernández2019b = DB(Work(
    2019, "Privacy-aware Linked Widgets",
    due="This paper aims to demonstrate the potential usage for verifying compliance using SPECIAL's policy language in the context of frameworks for defining Linked Data-based components. The authors extend this language in order to verify prospective compliance (i.e., before the process run). Since it does not propose a provenance model, we have considered it out of the scope.",
    display="garcia",
    authors="Fernandez Garcia, Javier David and Ekaputra, Fajar J and Aryan, Peb Ruswono and Azzam, Amr and Kiesling, Elmar",
    place=Book,
    ID='fernandez2019privacy',
    category='unrelated',
    cluster_id='13582822442266322658',
    entrytype='article',
    link='https://epub.wu.ac.at/6859/1/Privacy_aware_Linked_Data_Widgets___WWW_19__Camera_Ready.pdf',
    organization='ACM Press',
    scholar='https://scholar.google.com.br/scholar?cites=13582822442266322658&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='4uZ83gvhf7wJ',
    scholar_ok=True,
    forward_steps=1,
))

filippidis2019a = DB(Work(
    2019, "A Blockchain-Based Platform for Consent Management of Personal Data Processing in the IoT Ecosystem",
    due="Unrelated to provenance",
    display="filippidis",
    authors="Filippidis, Adam P and Rantos, Konstantinos and Papanikolaou, Alexandros and Ilioudis, Christos and Kritsas, Antonios and Drosatos, George",
    place=Thesis,
    ID='filippidis2019blockchain',
    category='unrelated',
    cluster_id='8666699689742166454',
    entrytype='article',
    link='http://hephaestus.nup.ac.cy/handle/11728/11753',
    organization='Wiley',
    scholar='https://scholar.google.com/scholar?cites=8666699689742166454&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='tukRHnNNRngJ',
    scholar_ok=True,
    forward_steps=1,
))

gallé2019a = DB(Work(
    2019, "The case for a GDPR-specific annotated dataset of privacy policies",
    due="Unrelated to provenance",
    display="gallé",
    authors="Gallé, Matthias and Christofi, Athena and Elsahar, Hady",
    place=PAL,
    ID='galle2019case',
    category='unrelated',
    cluster_id='8304496814992217200',
    entrytype='inproceedings',
    link='http://ceur-ws.org/Vol-2335/1st_PAL_paper_5.pdf',
    scholar='https://scholar.google.com/scholar?cites=8304496814992217200&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='cFT5p9p_P3MJ',
    scholar_ok=True,
    backward_steps=1,
))

garcia2019a = DB(Work(
    2019, "1st Workshop on Fairness, Accountability, Transparency, Ethics, and Society on the Web. In conjunction with The Web Conference 2019.",
    due="Unrelated to provenance",
    display="garcia",
    authors="Garcia, Javier David Fernandez and Ekaputra, Fajar J and Aryan, Peb Ruswono and Azzam, Amr and Kiesling, Elmar",
    place=FATES,
    ID='garcia20191st',
    category='unrelated',
    cluster_id='8215101330332997794',
    entrytype='incollection',
    link='https://research.wu.ac.at/ws/files/19835652/Privacy_aware_Linked_Data_Widgets___WWW_19__Camera_Ready.pdf',
    organization='ACM Press',
    pp='1--6',
    scholar='https://scholar.google.com/scholar?cites=8215101330332997794&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='olhWbCLnAXIJ',
    scholar_ok=True,
    forward_steps=1,
))

goldsteen2019a = DB(Work(
    2019, "Forgotten@ Scale: A Practical Solution for Implementing the Right To Be Forgotten in Large-Scale Systems",
    due="Not peer-reviewed document",
    display="goldsteen",
    authors="Goldsteen, Abigail and Douek, Tomer and Cohen, Yaniv and Gokhman, Igor and Keren-Ackerman, Ofir and Katsovich, Gadi and Weintraub, Grisha and Ben-Ari, Doron",
    place=arXiv,
    ID='goldsteen2019forgotten',
    category='unrelated',
    cluster_id='8712539456176012468',
    entrytype='article',
    link='https://arxiv.org/pdf/1910.13784',
    scholar='https://scholar.google.com.br/scholar?cites=8712539456176012468&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='tDzycHko6XgJ',
    scholar_ok=True,
    forward_steps=1,
))

hasan2019a = DB(Work(
    2019, "An Ontology based framework for e-Government regulatory requirements compliance",
    due="This paper is not available",
    display="hasan",
    authors="Hasan, M Mahmudul and Anagnostopoulos, Dimosthenis and Kousiouris, George and Stamati, Teta and Loucopoulos, Peri and Nikolaidou, Mara",
    place=IJESMA,
    ID='hasan2019ontology',
    category='nofile',
    cluster_id='9370060676057696091',
    entrytype='article',
    link='https://www.igi-global.com/article/an-ontology-based-framework-for-e-government-regulatory-requirements-compliance/225076',
    number='2',
    organization='IGI Global',
    pp='22--42',
    scholar='https://scholar.google.com.br/scholar?cites=9370060676057696091&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='W4dGSIokCYIJ',
    scholar_ok=True,
    volume='11',
    start_set=True,
))

havelange2019a = DB(Work(
    2019, "LUCE: A Blockchain Solution for monitoring data License accoUntability and CompliancE",
    due="unrelated to GDPR, provenance and not peer-reviewed",
    display="havelange",
    authors="Havelange, Andine and Dumontier, Michel and Wouters, Birgit and Linde, Jona and Townend, David and Riedl, Arno and Urovi, Visara",
    place=arXiv,
    ID='havelange2019luce',
    category='unrelated',
    cluster_id='3208619487027836085',
    entrytype='article',
    link='https://arxiv.org/pdf/1908.02287',
    scholar='https://scholar.google.com/scholar?cites=3208619487027836085&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='tbSwZ2xOhywJ',
    scholar_ok=True,
    backward_steps=1,
))

jafta2019a = DB(Work(
    2019, "A semantic tool for the protection of personal information act",
    due="This is a positional document and does not introduce any contribution",
    display="jafta",
    authors="Jafta, Yahlieel and Leenen, Louise",
    place=UnknownConference,
    ID='jafta2019semantic',
    category='unrelated',
    cluster_id='11356574413878000034',
    entrytype='article',
    link='http://ceur-ws.org/Vol-2540/FAIR2019_paper_36.pdf',
    scholar='https://scholar.google.com/scholar?cites=11356574413878000034&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='ovl8fEKomp0J',
    scholar_ok=True,
    forward_steps=1,
))

janßen2019a = DB(Work(
    2019, "Towards a system for data transparency to support data subjects",
    due="Document not publicly available",
    display="janßen",
    authors="Janßen, Christian",
    place=BIS,
    ID='janssen2019towards',
    category='nofile',
    cluster_id='15193073621556417676',
    entrytype='inproceedings',
    link='https://www.se.uni-oldenburg.de/documents/sumocos/presentations/sumocos_mn_2_3_2.pdf',
    organization='Springer',
    pp='613--624',
    scholar='https://scholar.google.com.br/scholar?cites=15193073621556417676&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='jFQ6Y_aj2NIJ',
    scholar_ok=True,
    forward_steps=1,
))

joshi2019a = DB(Work(
    2019, "Automating privacy compliance using policy integrated blockchain",
    due="Unrelated to provenance",
    display="joshi",
    authors="Joshi, Karuna Pande and Banerjee, Agniva",
    place=Cryptography,
    ID='joshi2019automating',
    category='unrelated',
    cluster_id='5178723869480249642',
    entrytype='article',
    link='https://www.mdpi.com/2410-387X/3/1/7/pdf',
    number='1',
    organization='Multidisciplinary Digital Publishing Institute',
    pp='7',
    scholar='https://scholar.google.com/scholar?cites=5178723869480249642&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='Kuk01uuF3kcJ',
    scholar_ok=True,
    volume='3',
    backward_steps=1,
))

kala2019a = DB(Work(
    2019, "Refinement of the general data protection regulation (GDPR) model: administrative fines perspective",
    due="Unrelated to provenance",
    display="kala",
    authors="Kala, Kaspar",
    place=Thesis,
    ID='kala2019refinement',
    category='unrelated',
    cluster_id='114316314360277640',
    entrytype='phdthesis',
    link='https://core.ac.uk/download/pdf/237084765.pdf',
    scholar='https://scholar.google.com/scholar?cites=114316314360277640&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='iOp5DRUilgEJ',
    scholar_ok=True,
    forward_steps=1,
))

leone2019a = DB(Work(
    2019, "Frequent Use Cases Extraction from Legal Texts in the Data Protection Domain.",
    due="Unrelated to provenance",
    display="leone",
    authors="Leone, Valentina and Di Caro, Luigi",
    place=JURIX,
    ID='leone2019frequent',
    category='unrelated',
    cluster_id='3349397256117784531',
    entrytype='inproceedings',
    link='https://iris.unito.it/bitstream/2318/1728643/1/FAIA-322-FAIA190324.pdf',
    pp='193--198',
    scholar='https://scholar.google.com/scholar?cites=3349397256117784531&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='04-R_g5zey4J',
    scholar_ok=True,
    forward_steps=1,
))

libertés2019a = DB(Work(
    2019, "The CNIL’s restricted committee imposes a financial penalty of 50 Million euros against GOOGLE LLC",
    due="File not found",
    display="libertés",
    authors="Commission Nationale de l’Informatique et des Libertés",
    place=UnknownConference,
    ID='commission2019cnil',
    category='nofile',
    entrytype='article',
    scholar_ok="@article{commission2019cnil,\n  title={The CNIL’s restricted committee imposes a financial penalty of 50 Million euros against GOOGLE LLC},\n  author={Commission Nationale de l’Informatique et des Libert{\\'e}s},\n  year={2019}\n}\n",
    backward_steps=1,
))

lieber2019a = DB(Work(
    2019, "Policy-compliant data processing: RDF-based restrictions for data-protection",
    due="This paper introces some discussion about the ontology engineering. Therfore, it is unrelated to our aims",
    display="lieber",
    authors="Lieber, Sven",
    place=ISWC,
    ID='lieber2019policy',
    category='unrelated',
    cluster_id='15972959278209968028',
    entrytype='inproceedings',
    link='https://biblio.ugent.be/publication/8722400/file/8722401',
    pp='1--12',
    scholar='https://scholar.google.com/scholar?cites=15972959278209968028&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='nCd8zdVZq90J',
    scholar_ok=True,
    backward_steps=1,
))

lioudakis2019a = DB(Work(
    2019, "Compliance Ontology",
    due="Discarded due to the document was not publicly available. This paper reports the ontology used by the BPR4GDPR (Business Process Re-engineering and functional toolkit for GDPR compliance), a European H2020 project that aims to provide a reference compliance framework for the GDPR. This ontology is designed to collect retrospective and prospective provenance. However, it lacks provide concepts capable of representing the legal basis for a process. ",
    display="lioudakis",
    authors="Lioudakis, Georgios and Cascone, D",
    place=ARIS2,
    ID='lioudakis2019compliance',
    cluster_id='13951300420119684617',
    entrytype='article',
    link='https://www.bpr4gdpr.eu/wp-content/uploads/2019/06/D3.1-Compliance-Ontology-1.0.pdf',
    scholar='https://scholar.google.com/scholar?cites=13951300420119684617&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='Ceb9n9D5nMEJ',
    scholar_ok=True,
    volume='1',
    category="unrelated",
    useful=True,
    not_directly_related_to_provenance=True,
    backward_steps=1,
))

machuletz2019a = DB(Work(
    2019, "Multiple purposes, multiple problems: A user study of consent dialogs after GDPR",
    due="Not peer-reviewed document",
    display="machuletz",
    authors="Machuletz, Dominique and Böhme, Rainer",
    place=arXiv,
    ID='machuletz2019multiple',
    category='unrelated',
    cluster_id='9816585992241849936',
    entrytype='article',
    link='https://arxiv.org/pdf/1908.10048',
    scholar='https://scholar.google.com/scholar?cites=9816585992241849936&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='UKamDvOEO4gJ',
    scholar_ok=True,
    backward_steps=1,
))

mehr2019a = DB(Work(
    2019, "Compliance to Data Protection and Purpose Control Using Process Mining Technique.",
    due="Unrelated to provenance",
    display="mehr",
    authors="Mehr, Azadeh Sadat Mozafari",
    place=BPM,
    ID='mehr2019compliance',
    category='unrelated',
    cluster_id='3966423398095975249',
    entrytype='inproceedings',
    link='http://ceur-ws.org/Vol-2420/papeDC10.pdf',
    pp='108--113',
    scholar='https://scholar.google.com/scholar?cites=3966423398095975249&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='UfNOyBCRCzcJ',
    scholar_ok=True,
    backward_steps=1,
))

merscheid2019a = DB(Work(
    2019, "Practical Combination of IT Security, Risk Management, and EU Data Protection (GDPR)",
    due="Unrelated to provenance and ",
    display="merscheid",
    authors="Merscheid, Tim",
    place=Thesis,
    ID='merscheid2019practical',
    category='unrelated',
    cluster_id='438355628799429348',
    entrytype='phdthesis',
    link='https://www.researchgate.net/profile/Tim-Merscheid/publication/338753440_Practical_Combination_of_IT_Security_Risk_Management_and_EU_Data_Protection_GDPR/links/5e28b4114585150ee77b2af5/Practical-Combination-of-IT-Security-Risk-Management-and-EU-Data-Protection-GDPR.pdf',
    scholar='https://scholar.google.com/scholar?cites=438355628799429348&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='5AriMx9aFQYJ',
    scholar_ok=True,
    forward_steps=1,
))

mohammadi2019a = DB(Work(
    2019, "Privacy policy specification framework for addressing end-users’ privacy requirements",
    due="FIle not found",
    display="mohammadi",
    authors="Gol Mohammadi, Nazila and Leicht, Jens and Ulfat-Bunyadi, Nelufar and Heisel, Maritta",
    place=TrustBus,
    ID='gol2019privacy',
    category='nofile',
    cluster_id='14328840167722937959',
    entrytype='inproceedings',
    link='https://link.springer.com/chapter/10.1007/978-3-030-27813-7_4',
    organization='Springer',
    pp='46--62',
    scholar='https://scholar.google.com/scholar?cites=14328840167722937959&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='Z255EDdE2sYJ',
    scholar_ok=True,
    backward_steps=1,
))

pandit2019a = DB(Work(
    2019, "GConsent-a consent ontology based on the GDPR",
    due="This approach introduces an ontology to represent consent states (e.g. unknown, given, withdrawn). However, this document is not available.",
    display="pandit",
    authors="Pandit, Harshvardhan J and Debruyne, Christophe and O’Sullivan, Declan and Lewis, Dave",
    place=ESWC,
    ID='pandit2019gconsent',
    category='unrelated',
    cluster_id='18164481854340998123',
    entrytype='inproceedings',
    link='https://link.springer.com/chapter/10.1007/978-3-030-21348-0_18',
    organization='Springer',
    pp='270--282',
    scholar='https://scholar.google.com.br/scholar?cites=18164481854340998123&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='6yMGyQE0FfwJ',
    scholar_ok=True,
    summary='Consent is one of the legal basis for processing personal data under the General Data Protection Regulation (GDPR), which is the current Eurpoean data protection law enforced from 25th May 2018. GDPR stipulates obligations on how consent should be obtained, used, modified, and recorded. Additionally, it provides data subjects with the right to modify or withdraw their consent at any time. Demonstrating compliance to these rights and obligations requires maintaining information about the consent lifecycle. Existing work has demonstrated the feasibility of using semantic web technologies to represent and query this information. GConsent is an OWL2 ontology for representing consent for GDPR compliance. The ontology is based on an analysis of modelling metadata requirements related to the consent lifecycle for GDPR compliance. It allows modelling and representation of information related to compliance in an extensible and comprehensive manner.',
    start_set=True,
))

pandit2019b = DB(Work(
    2019, "Test-driven approach towards gdpr compliance",
    due="This contribution do not propose ontologies or provenance model related to GDPR, but utilizes from prior contributuions and shows how to these might be instantiated into a real use-case",
    display="pandit",
    authors="Pandit, Harshvardhan J and O’Sullivan, Declan and Lewis, Dave",
    place=SEMANTiCS,
    ID='pandit2019test',
    category='unrelated',
    cluster_id='8030589381850549172',
    entrytype='inproceedings',
    link='https://link.springer.com/chapter/10.1007/978-3-030-33220-4_2',
    organization='Springer',
    pp='19--33',
    scholar='https://scholar.google.com.br/scholar?cites=8030589381850549172&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='tMs5sn5icm8J',
    scholar_ok=True,
    start_set=True,
))

pandit2019c = DB(Work(
    2019, "Creating a vocabulary for data privacy",
    due="Not directly related to provenance. This approach provides a privacy vocabularies the GDPR. This vocabulari is make available under https://w3c.github.io/dpv/dpv/.",
    display="DPV",
    authors="Pandit, Harshvardhan J and Polleres, Axel and Bos, Bert and Brennan, Rob and Bruegger, Bud and Ekaputra, Fajar J and Fernández, Javier D and Hamed, Roghaiyeh Gachpaz and Kiesling, Elmar and Lizar, Mark and others",
    place=arXiv,
    ID='pandit2019creating',
    category='unrelated',
    cluster_id='9799703764205422827',
    entrytype='inproceedings',
    link='https://aic.ai.wu.ac.at/~polleres/publications/pand-etal-2019ODBASE.pdf',
    organization='Springer',
    pp='714--730',
    scholar='https://scholar.google.com.br/scholar?cites=9799703764205422827&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='68iFCaeK_4cJ',
    scholar_ok=True,
    useful=True,
    not_directly_related_to_provenance=True,
    backward_steps=1,
))

pennekamp2019a = DB(Work(
    2019, "Security considerations for collaborations in an industrial IoT-based lab of labs",
    due="unrelated to GDPR",
    display="pennekamp",
    authors="Pennekamp, Jan and Dahlmanns, Markus and Gleim, Lars and Decker, Stefan and Wehrle, Klaus",
    place=GCIoT,
    ID='pennekamp2019security',
    category='unrelated',
    cluster_id='11881268964828440245',
    entrytype='inproceedings',
    link='https://www.mdahlmanns.de/publication/2019-pennekamp-security-considerations/2019-pennekamp-security-considerations.pdf',
    organization='IEEE',
    pp='1--7',
    scholar='https://scholar.google.com/scholar?cites=11881268964828440245&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='teZ4gSy_4qQJ',
    scholar_ok=True,
    forward_steps=1,
))

piras2019a = DB(Work(
    2019, "DEFeND architecture: a privacy by design platform for GDPR compliance",
    due="Unrelated to provenance",
    display="piras",
    authors="Piras, Luca and Al-Obeidallah, Mohammed Ghazi and Praitano, Andrea and Tsohou, Aggeliki and Mouratidis, Haralambos and Gallego-Nicasio Crespo, Beatriz and Bernard, Jean Baptiste and Fiorani, Marco and Magkos, Emmanouil and Sanz, Andres Castillo and others",
    place=TrustBus,
    ID='piras2019defend',
    category='unrelated',
    cluster_id='11735155084072539261',
    entrytype='inproceedings',
    link='https://rgu-repository.worktribe.com/preview/1238925/PIRAS%202019%20DEFeND%20architecture.pdf',
    organization='Springer',
    pp='78--93',
    scholar='https://scholar.google.com/scholar?cites=11735155084072539261&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='fVRDml-l26IJ',
    scholar_ok=True,
    backward_steps=1,
))

pullonen2019a = DB(Work(
    2019, "Privacy-enhanced BPMN: enabling data privacy analysis in business processes models",
    due="Not publicly available",
    display="pullonen",
    authors="Pullonen, Pille and Tom, Jake and Matulevicius, Raimundas and Toots, Aivo",
    place=SSM,
    ID='pullonen2019privacy',
    category='nofile',
    cluster_id='6409572784300962227',
    entrytype='article',
    link='https://link.springer.com/article/10.1007/s10270-019-00718-z',
    number='6',
    organization='Springer',
    pp='3235--3264',
    scholar='https://scholar.google.com/scholar?cites=6409572784300962227&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='szFF6nxg81gJ',
    scholar_ok=True,
    volume='18',
    backward_steps=1,
))

rantos2019a = DB(Work(
    2019, "A blockchain-based platform for consent management of personal data processing in the IoT ecosystem",
    due="Unrelated to provenance",
    display="rantos",
    authors="Rantos, Konstantinos and Drosatos, George and Kritsas, Antonios and Ilioudis, Christos and Papanikolaou, Alexandros and Filippidis, Adam P",
    place=JSCN,
    ID='rantos2019blockchain',
    category='unrelated',
    cluster_id='4977037163942878668',
    entrytype='article',
    link='https://www.hindawi.com/journals/scn/2019/1431578/',
    organization='Hindawi',
    scholar='https://scholar.google.com/scholar?cites=4977037163942878668&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='zJ27Xu78EUUJ',
    scholar_ok=True,
    volume='2019',
    forward_steps=1,
))

rantos2019b = DB(Work(
    2019, "Research Article A Blockchain-Based Platform for Consent Management of Personal Data Processing in the IoT Ecosystem",
    due="unrelated to GDPR",
    display="rantos",
    authors="Rantos, Konstantinos and Drosatos, George and Kritsas, Antonios and Ilioudis, Christos and Papanikolaou, Alexandros and Filippidis, Adam P",
    place=JSCN,
    ID='rantos2019research',
    category='unrelated',
    cluster_id='12181928461946548708',
    entrytype='article',
    link='https://www.academia.edu/download/64343659/1431578.pdf',
    scholar='https://scholar.google.com/scholar?cites=12181928461946548708&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='5HGLvWTnDqkJ',
    scholar_ok=True,
    forward_steps=1,
))

reinhartz2019a = DB(Work(
    2019, "Towards Privacy-aware Software Reuse.",
    due="Unrelated to provenance",
    display="reinhartz",
    authors="Reinhartz-Berger, Iris and Zamansky, Anna and Koschmider, Agnes",
    place=MODELSWARD,
    ID='reinhartz2019towards',
    category='unrelated',
    cluster_id='1754949847576754345',
    entrytype='inproceedings',
    link='https://pdfs.semanticscholar.org/e451/ea2a17123c572105ebd15be5a497fc43832b.pdf',
    pp='448--453',
    scholar='https://scholar.google.com/scholar?cites=1754949847576754345&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='qThwl5bVWhgJ',
    scholar_ok=True,
    forward_steps=1,
))

riva2019a = DB(Work(
    2019, "Privacy architecting of GDPR-compliant high-tech systems: the PAGHS methodology",
    summary="The work propose a architecture and a methodology to acheive compliance with GDPR.",
    display="riva",
    authors="Riva, Giovanni Maria",
    place=Thesis,
    ID='riva2019privacy',
    category='unrelated',
    cluster_id='1541122321598295249',
    entrytype='mastersthesis',
    link='http://essay.utwente.nl/79359/1/Riva_MA_EEMCS.pdf',
    scholar='https://scholar.google.com/scholar?cites=1541122321598295249&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='0axKFpYqYxUJ',
    scholar_ok=True,
    due="Not related to data provenance.",
    forward_steps=1,
))

rodrigues2019a = DB(Work(
    2019, "Legal ontologies over time: A systematic mapping study",
    due="unrelated to GDPR and document not available",
    display="rodrigues",
    authors="de Oliveira Rodrigues, Cleyton Mario and de Freitas, Frederico Luiz Goncalves and Barreiros, Emanoel Francisco Sposito and de Azevedo, Ryan Ribeiro and de Almeida Filho, Adauto Trigueiro",
    place=ESA,
    ID='de2019legal',
    category='unrelated',
    cluster_id='3828102233904234148',
    entrytype='article',
    link='https://www.sciencedirect.com/science/article/pii/S0957417419302398',
    organization='Elsevier',
    pp='12--30',
    scholar='https://scholar.google.com/scholar?cites=3828102233904234148&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='pL69F7MmIDUJ',
    scholar_ok=True,
    volume='130',
    backward_steps=1,
))

rodrigues2019b = DB(Work(
    2019, "Uma abordagem ontologica para simulação de acao legal e consistencia semântica aplicada a legislacao brasileira",
    due="unrelated to GDPR",
    display="rodrigues",
    authors="RODRIGUES, Cleyton Mario de Oliveira",
    place=Thesis,
    ID='rodrigues2019abordagem',
    category='unrelated',
    cluster_id='15179458466387900462',
    entrytype='article',
    link='https://repositorio.ufpe.br/bitstream/123456789/33904/1/TESE%20Cleyton%20M%C3%A1rio%20de%20Oliveira%20Rodrigues.pdf',
    organization='Universidade Federal de Pernambuco',
    scholar='https://scholar.google.com/scholar?cites=15179458466387900462&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='LrjYCw1FqNIJ',
    scholar_ok=True,
    forward_steps=1,
))

rossi2019a = DB(Work(
    2019, "DaPIS: an ontology-based data protection icon set",
    due="Unrelated to provenance",
    display="rossi",
    authors="Rossi, Arianna and Palmirani, Monica",
    place=Book,
    ID='rossi2019dapis',
    category='unrelated',
    cluster_id='12002446090753593784',
    entrytype='article',
    link='https://orbilu.uni.lu/bitstream/10993/40117/1/dapis-lvi18%20printed.pdf',
    organization='IOS Press',
    pp='181',
    scholar='https://scholar.google.com/scholar?cites=12002446090753593784&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='uNEkuyBBkaYJ',
    scholar_ok=True,
    volume='317',
    backward_steps=1,
))

schaefer2019a = DB(Work(
    2019, "Transparent logging with hyperledger fabric",
    due="Unrelated to provenance",
    display="schaefer",
    authors="Schaefer, Christian and Edman, Christine",
    place=ICBC,
    ID='schaefer2019transparent',
    category='unrelated',
    cluster_id='3004937027309908162',
    entrytype='inproceedings',
    link='https://ieeexplore.ieee.org/abstract/document/8751339/',
    organization='IEEE',
    pp='65--69',
    scholar='https://scholar.google.com/scholar?cites=3004937027309908162&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='wrA5NU6usykJ',
    scholar_ok=True,
    forward_steps=1,
))

shastri2019a = DB(Work(
    2019, "Understanding and benchmarking the impact of GDPR on database systems",
    due="Document not peer-reviwed",
    display="shastri",
    authors="Shastri, Supreeth and Banakar, Vinay and Wasserman, Melissa and Kumar, Arun and Chidambaram, Vijay",
    place=arXiv,
    ID='shastri2019understanding',
    category='unrelated',
    cluster_id='12012978714918272380',
    entrytype='article',
    link='https://arxiv.org/pdf/1910.00728',
    scholar='https://scholar.google.com/scholar?cites=12012978714918272380&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='fD0IZX6stqYJ',
    scholar_ok=True,
    backward_steps=1,
))

sion2019a = DB(Work(
    2019, "An architectural view for data protection by design",
    due="Unrelated to provenance",
    display="sion",
    authors="Sion, Laurens and Dewitte, Pierre and Van Landuyt, Dimitri and Wuyts, Kim and Emanuilov, Ivo and Valcke, Peggy and Joosen, Wouter",
    place=IEEEBD,
    ID='sion2019architectural',
    category='unrelated',
    cluster_id='11870001569083420875',
    entrytype='inproceedings',
    link='https://lirias.kuleuven.be/retrieve/533826',
    organization='IEEE',
    pp='11--20',
    scholar='https://scholar.google.com/scholar?cites=11870001569083420875&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='y_CLgIm3uqQJ',
    scholar_ok=True,
    backward_steps=1,
))

stoykov2019a = DB(Work(
    2019, "Legal data extraction and possible applications",
    due="Does not propose a model",
    display="stoykov",
    authors="Stoykov, K and Chelebieva, S",
    place=IOPMSE,
    ID='stoykov2019legal',
    category='unrelated',
    cluster_id='1360870846515387519',
    entrytype='inproceedings',
    link='https://iopscience.iop.org/article/10.1088/1757-899X/618/1/012037/pdf',
    number='1',
    organization='IOP Publishing',
    pp='012037',
    scholar='https://scholar.google.com/scholar?cites=1360870846515387519&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='fxy8H9PI4hIJ',
    scholar_ok=True,
    volume='618',
    forward_steps=1,
))

tambou2019a = DB(Work(
    2019, "Open Access Book on National Adaptations of the GDPR, Mc Cullagh, Tambou, Bourton – blogdroiteuropeen",
    due="Not a peer-reviewed publication",
    display="tambou",
    authors="Olivia Tambou",
    place=Web,
    ID='OpenAcce67:online',
    category='unrelated',
    entrytype='misc',
    scholar_ok='@misc{OpenAcce67:online,\nauthor = {Olivia Tambou},\ntitle = {Open Access Book on National Adaptations of the GDPR, Mc Cullagh, Tambou, Bourton – blogdroiteuropeen},\nhowpublished = {https://blogdroiteuropeen.com/2019/02/27/open-access-book-on-national-adaptations-of-the-gdpr-mc-cullagh-tambou-bourton-eds/},\nmonth = {},\nyear = {2019},\n}',
    backward_steps=1,
))

torre2019a = DB(Work(
    2019, "Using models to enable compliance checking against the GDPR: an experience report",
    due="The ontology was not publicly available",
    display="torre",
    authors="Torre, Damiano and Soltana, Ghanem and Sabetzadeh, Mehrdad and Briand, Lionel C and Auffinger, Yuri and Goes, Peter",
    place=MODELS,
    ID='torre2019using',
    category='nofile',
    cluster_id='14933488079857526002',
    entrytype='inproceedings',
    link='https://orbilu.uni.lu/bitstream/10993/39701/1/PID6018521.pdf',
    organization='IEEE',
    pp='1--11',
    scholar='https://scholar.google.com/scholar?cites=14933488079857526002&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='8iRwoUloPs8J',
    scholar_ok=True,
    forward_steps=1,
))

truong2019a = DB(Work(
    2019, "Gdpr-compliant personal data management: A blockchain-based solution",
    due="Unrelated to data provenance.",
    display="truong",
    authors="Truong, Nguyen Binh and Sun, Kai and Lee, Gyu Myoung and Guo, Yike",
    place=arXiv,
    ID='truong2019gdpr',
    category='unrelated',
    cluster_id='10220035432706323055',
    entrytype='article',
    link='https://ieeexplore.ieee.org/iel7/10206/8833568/08876647.pdf',
    organization='IEEE',
    pp='1746--1761',
    scholar='https://scholar.google.com.br/scholar?cites=10220035432706323055&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='b7Jd9hPc1I0J',
    scholar_ok=True,
    volume='15',
    start_set=True,
))

ujcich2019a = DB(Work(
    2019, "Data protection intents for software-defined networking",
    due="Not related to data provenance.",
    summary="The work is concerned with the personal-data-transfer aspect included in the definition of processing by the GDPR. Its solution is a framework for an intent-based network (IBN) that is focused on four goals: (1) Specify host-to-host data plane connection requests for data processing through data protection abstractions; (2) Maintain observance and oversight over all network requests that involve personal data; (3) Log control plane and data plane events to bridge network abstractions and data protection abstractions; (4) Use data protection abstractions to query past events for analysis and forensics.",
    display="ujcich (IBN)",
    authors="Ujcich, Benjamin E and Sanders, William H",
    place=IEEENetSoft,
    ID='ujcich2019data',
    category='unrelated',
    cluster_id='7822871336782130335',
    entrytype='inproceedings',
    link='https://www.perform.illinois.edu/Papers/USAN_papers/19UJC01.pdf',
    organization='IEEE',
    pp='271--275',
    scholar='https://scholar.google.com/scholar?cites=7822871336782130335&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='n-x7kAhskGwJ',
    scholar_ok=True,
    forward_steps=1,
))

urm2019a = DB(Work(
    2019, "Initial Specification of BPR4GDPR architecture",
    due="Not directly related to provenace",
    display="urm",
    authors="URM, Lorenzo Bracciale and CAS, Adrián Juan-Verdejo",
    place=Web,
    ID='urm2019initial',
    category='unrelated',
    entrytype='article',
    pdfpage="@article{urm2019initial,\n  title={Initial Specification of BPR4GDPR architecture},\n  author={URM, Lorenzo Bracciale and CAS, Adri{\\'a}n Juan-Verdejo},\n  year={2019}\n}\n",
    scholar_ok="@article{urm2019initial,\n  title={Initial Specification of BPR4GDPR architecture},\n  author={URM, Lorenzo Bracciale and CAS, Adri{\\'a}n Juan-Verdejo},\n  year={2019}\n}\n",
    backward_steps=1,
))

utz2019a = DB(Work(
    2019, "(Un) informed consent: Studying GDPR consent notices in the field",
    due="Unrelated to provenance",
    display="utz",
    authors="Utz, Christine and Degeling, Martin and Fahl, Sascha and Schaub, Florian and Holz, Thorsten",
    place=CCS,
    ID='utz2019informed',
    category='unrelated',
    cluster_id='577201127467320173',
    entrytype='inproceedings',
    link='https://dl.acm.org/doi/pdf/10.1145/3319535.3354212',
    pp='973--990',
    scholar='https://scholar.google.com/scholar?cites=577201127467320173&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='bQOlBl6hAggJ',
    scholar_ok=True,
    backward_steps=1,
))

vos2019a = DB(Work(
    2019, "ODRL policy modelling and compliance checking",
    due="ODRL serves as a background for our purposes rather than a possible approach. ODRL makes it capable of representing GDPR policy rules (rights, obligations, etc.), but it is not the aim of this paper to represent the GDPR itself. Instead, this paper only uses some obligations from the GDPR to validate the ODRL. Additionally, it also demonstrates how to check compliance by using ODRL.",
    display="vos",
    authors="Vos, Marina De and Kirrane, Sabrina and Padget, Julian and Satoh, Ken",
    place=IJCRR,
    ID='vos2019odrl',
    category='unrelated',
    cluster_id='3853891893177523865',
    entrytype='inproceedings',
    link='https://epub.wu.ac.at/7078/1/RuleML%2BRR_2019_Final.pdf',
    organization='Springer',
    pp='36--51',
    scholar='https://scholar.google.com.br/scholar?cites=3853891893177523865&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='mZ6aD0LGezUJ',  
    start_set=True,
    scholar_ok=True,
))

wang2019a = DB(Work(
    2019, "Data capsule: A new paradigm for automatic compliance with data privacy regulations",
    due="Unrelated to provenance",
    display="wang",
    authors="Wang, Lun and Near, Joseph P and Somani, Neel and Gao, Peng and Low, Andrew and Dao, David and Song, Dawn",
    place=VLDB,
    ID='wang2019data',
    category='unrelated',
    cluster_id='17119379763499216965',
    entrytype='incollection',
    link='https://arxiv.org/pdf/1909.00077',
    organization='Springer',
    pp='3--23',
    scholar='https://scholar.google.com/scholar?cites=17119379763499216965&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='RbBhSjFBlO0J',
    scholar_ok=True,
    backward_steps=1,
))

weissgerber2019a = DB(Work(
    2019, "A balanced scorecard for holistic monitoring of shared services for corporate data protection",
    due="Unrelated to provenance",
    display="weissgerber",
    authors="Weissgerber, Florian and Lazar, Eszter and Tafreschi, Omid",
    place=ICBIM,
    ID='weissgerber2019balanced',
    category='unrelated',
    cluster_id='13193113802828808785',
    entrytype='inproceedings',
    link='https://dl.acm.org/doi/pdf/10.1145/3361785.3361793?casa_token=Br301A48Lf0AAAAA:6mgJ78zMv3IDAf34xR5BeZTHsPF5djM1yBpGCly2NVCZgEsUO9br9qFUgyQMzjhzJMLc75Bw0vKN7Q',
    pp='152--157',
    scholar='https://scholar.google.com/scholar?cites=13193113802828808785&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='UQLqghpbF7cJ',
    scholar_ok=True,
    forward_steps=1,
))

wilhelm2019a = DB(Work(
    2019, "Policy-based authentication and authorization based on the layered privacy language",
    due="Unrelated to provenance",
    display="wilhelm",
    authors="Wilhelm, Sebastian and Gerl, Armin",
    place=BTW,
    ID='wilhelm2019policy',
    category='unrelated',
    cluster_id='1356794880405329328',
    entrytype='article',
    link='https://dl.gi.de/bitstream/handle/20.500.12116/21812/D1-9.pdf?sequence=1&isAllowed=y',
    organization='Gesellschaft für Informatik, Bonn',
    scholar='https://scholar.google.com/scholar?cites=1356794880405329328&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='sNWgT8FN1BIJ',
    scholar_ok=True,
    forward_steps=1,
))

winckler2019a = DB(Work(
    2019, "Personal Information Controller Service (PICS)",
    due="File not found",
    display="winckler",
    authors="Winckler, Marco and Goncalves, Laurent and Nicolas, Olivier and Biennier, Frédérique and Benfenatki, Hind and Despeyroux, Thierry and Alaya, Nourhène and Deslée, Alex and Diallo, Mbaye Fall and Collin-Lachaud, Isabelle and others",
    place=ICWE,
    ID='winckler2019personal',
    category='nofile',
    cluster_id='15465082773171316680',
    entrytype='inproceedings',
    link='https://link.springer.com/chapter/10.1007/978-3-030-19274-7_40',
    organization='Springer',
    pp='530--533',
    scholar='https://scholar.google.com/scholar?cites=15465082773171316680&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='yKfjPNgCn9YJ',
    scholar_ok=True,
    backward_steps=1,
))


yeung2019a = DB(Work(
    2019, "Effects of inserting domain vocabulary and fine-tuning BERT for German legal language",
    due="unrelated to GDPR",
    display="yeung",
    authors="Yeung, Chin Man",
    place=Thesis,
    ID='yeung2019effects',
    category='unrelated',
    cluster_id='14308796113609245603',
    entrytype='mastersthesis',
    link='http://essay.utwente.nl/80128/1/Yeung_InteractionTechnology_EEMCS.pdf',
    scholar='https://scholar.google.com/scholar?cites=14308796113609245603&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='o0MrC0EOk8YJ',
    scholar_ok=True,
    forward_steps=1,
))

zhao2019a = DB(Work(
    2019, "Towards a computer-interpretable actionable formal model to encode data governance rules",
    due="Not related to data provenance.",
    display="zhao",
    authors="Zhao, Rui and Atkinson, Malcolm",
    place=eSCIENCEandGRID,
    ID='zhao2019towards',
    category='unrelated',
    cluster_id='7976200737766842341',
    entrytype='inproceedings',
    link='https://arxiv.org/pdf/1911.08439',
    organization='IEEE',
    pp='594--603',
    scholar='https://scholar.google.com/scholar?cites=7976200737766842341&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='5R_Nr08osW4J',
    scholar_ok=True,
    forward_steps=1,
))
