# coding: utf-8
from datetime import datetime
from snowballing.models import *
from ..places import *

bates2017a = DB(Work(
    2017, "Transparent web service auditing via network provenance functions",
    due="unrelated to GDPR",
    display="bates",
    authors="Bates, Adam and Hassan, Wajih Ul and Butler, Kevin and Dobra, Alin and Reaves, Bradley and Cable, Patrick and Moyer, Thomas and Schear, Nabil",
    place=WWW,
    ID='bates2017transparent',
    category='unrelated',
    cluster_id='6955665710699725764',
    entrytype='inproceedings',
    link='https://dl.acm.org/doi/pdf/10.1145/3038912.3052640',
    pp='887--895',
    scholar='https://scholar.google.com/scholar?cites=6955665710699725764&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='xEOfdhx9h2AJ',
    scholar_ok=True,
    backward_steps=1,
))

bonatti2017a = DB(Work(
    2017, "Transparent personal data processing: The road ahead",
    due="Unrelated to provenance",
    display="bonatti",
    authors="Bonatti, Piero and Kirrane, Sabrina and Polleres, Axel and Wenning, Rigo",
    place=SAFECOMP,
    ID='bonatti2017transparent',
    category='unrelated',
    cluster_id='14938317106682182647',
    entrytype='inproceedings',
    link='https://epub.wu.ac.at/6486/1/TELERISE-Transparent.pdf',
    organization='Springer',
    pp='337--349',
    scholar='https://scholar.google.com/scholar?cites=14938317106682182647&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='97vuDUOQT88J',
    scholar_ok=True,
    backward_steps=1,
))

cardellino2017a = DB(Work(
    2017, "Legal NERC with ontologies, Wikipedia and curriculum learning",
    due="Not peer-reviewed",
    display="cardellino",
    authors="Cardellino, Cristian and Teruel, Milagro and Alemany, Laura and Villata, Serena",
    place=HAL,
    ID='cardellino2017legal',
    category='unrelated',
    cluster_id='16889922767102279548',
    entrytype='inproceedings',
    link='https://hal.archives-ouvertes.fr/hal-01572444/document',
    pp='254--259',
    scholar='https://scholar.google.com/scholar?cites=16889922767102279548&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='fP_pIEUPZeoJ',
    scholar_ok=True,
    backward_steps=1,
))

casanovasabc2017a = DB(Work(
    2017, "Legal compliance by design (LCbD) and through design (LCtD): preliminary survey",
    due="Unrelated to provenance",
    display="casanovasabc",
    authors="Casanovasabc, Pompeu and González-Conejeroc, Jorge and de Kokerab, Louis",
    place=TRC,
    ID='casanovasabc2017legal',
    category='unrelated',
    cluster_id='8007834280982932009',
    entrytype='article',
    link='http://ceur-ws.org/Vol-2049/05paper.pdf',
    scholar='https://scholar.google.com/scholar?cites=8007834280982932009&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='Keou6tmKIW8J',
    scholar_ok=True,
    backward_steps=1,
))

diamantopoulou2017a = DB(Work(
    2017, "A Metamodel for GDPR-based Privacy Level Agreements.",
    due="Unrelated to Provenance",
    display="diamantopoulou",
    authors="Diamantopoulou, Vasiliki and Angelopoulos, Konstantinos and Pavlidis, Michalis and Mouratidis, Haralambos",
    place=UnknownConference,
    ID='diamantopoulou2017metamodel',
    category='unrelated',
    cluster_id='13082898839281596376',
    entrytype='inproceedings',
    link='http://ceur-ws.org/Vol-1979/paper-08.pdf',
    pp='285--291',
    scholar='https://scholar.google.com/scholar?cites=13082898839281596376&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='2Pe_my3Lj7UJ',
    scholar_ok=True,
    volume='1979',
    backward_steps=1,
))

echevarria2017a = DB(Work(
    2017, "D6.7FinalProductVersionofSecurityAwareToolsv1.0_77_378.pdf",
    due="Unrelated to provenance",
    authors="Leire Orue-Echevarria, Gorka Echevarria, Gorka Benguria, Juncal Alonso",
    place=Web,
    ID='D67Final71:online',
    category='unrelated',
    entrytype='misc',
    month='4',
    scholar_ok='@misc{D67Final71:online,\nauthor = {Matt Gallagher (OCC), Paul Grace (ITI), Constantinos Patsakis (UPRC), Sinica Alboaie (RMS), Leire Orue-Echevarria (TCN), Gorka Echevarria (TCN), Gorka Benguria (TCN)},\ntitle = {D6.7FinalProductVersionofSecurityAwareToolsv1.0\\_77\\_378.pdf},\nhowpublished = {http://www.operando.eu/upload/operando/moduli/D6.7FinalProductVersionofSecurityAwareToolsv1.0_77_378.pdf},\nmonth = {4},\nyear = {2017},\n}',
    backward_steps=1,
))

fatema2017a = DB(Work(
    2017, "Compliance through Informed Consent: Semantic Based Consent Permission and Data Management Model.",
    due="This approach presents an ontology to represent the activities, consent and permissions.",
    display="fatema",
    authors="Fatema, Kaniz and Hadziselimovic, Ensar and Pandit, Harshvardhan J and Debruyne, Christophe and Lewis, Dave and O'Sullivan, Declan",
    place=ISWC,
    ID='fatema2017compliance',
    category='ok',
    cluster_id='7851795297572476037',
    entrytype='inproceedings',
    link='http://www.tara.tcd.ie/bitstream/handle/2262/82659/88248c5b669175f267069c3319d9ac2d3e84.pdf?sequence=1',
    scholar='https://scholar.google.com.br/scholar?cites=7851795297572476037&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='hdTj-Dgu92wJ',
    scholar_ok=True,
    summary="focused in the representation of consent and permissions",
    start_set=True,
))

gandon2017a = DB(Work(
    2017, "Normative requirements as linked data",
    due="unrelated to GDPR",
    display="gandon",
    authors="Gandon, Fabien and Governatori, Guido and Villata, Serena",
    place=JURIX,
    ID='gandon2017normative',
    category='unrelated',
    cluster_id='9712672567287924634',
    entrytype='inproceedings',
    link='https://hal.archives-ouvertes.fr/hal-01643769/document',
    pp='1--10',
    scholar='https://scholar.google.com/scholar?cites=9712672567287924634&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='msfgcD1YyoYJ',
    scholar_ok=True,
    backward_steps=1,
))

garijo2017a = DB(Work(
    2017, "WIDOCO: a wizard for documenting ontologies",
    due="unrelated to GDPR",
    display="garijo",
    authors="Garijo, Daniel",
    place=ISWC,
    ID='garijo2017widoco',
    category='unrelated',
    cluster_id='6284308090736063162',
    entrytype='inproceedings',
    link='https://drive.google.com/file/d/18UHZYZRG4ReLj57Qzw6-PTVS4ZveFuWv/view',
    organization='Springer',
    pp='94--102',
    scholar='https://scholar.google.com/scholar?cites=6284308090736063162&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='urJvr-lYNlcJ',
    scholar_ok=True,
    backward_steps=1,
))

gu2017a = DB(Work(
    2017, "D3. 1 General Legal Aspects",
    due="Unrelated to provenance and not a peer-reviewed document",
    display="Scalable Oblivious Data Analytics",
    authors="GU, Gerald Spindler and GU, Anna Zsófia Horváth and GU, Lukas Dalby",
    place=Web,
    ID='citation-0',
    category='unrelated',
    cluster_id='5824696163975323470',
    entrytype='article',
    link='https://www.soda-project.eu/wp-content/uploads/2018/02/SODA-D3.1-General-Legal-Aspects.pdf',
    scholar='https://scholar.google.com/scholar?cites=5824696163975323470&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='Tl9U8kx61VAJ',
    scholar_ok=True,
    backward_steps=1,
))

gurk2017a = DB(Work(
    2017, "Towards Ontology Quality Assessment.",
    due="unrelated to GDPR",
    display="gurk",
    authors="Mc Gurk, Silvio and Abela, Charlie and Debattista, Jeremy",
    place=ESWC,
    ID='mc2017towards',
    category='unrelated',
    cluster_id='15781285807826769546',
    entrytype='inproceedings',
    link='https://www.researchgate.net/profile/Silvio-Mc-Gurk/publication/319007298_Towards_Ontology_Quality_Assessment/links/598ada2a45851519f10d7ca6/Towards-Ontology-Quality-Assessment.pdf',
    pp='94--106',
    scholar='https://scholar.google.com/scholar?cites=15781285807826769546&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='ipZtUtRjAtsJ',
    scholar_ok=True,
    backward_steps=1,
))

gutierrez2017a = DB(Work(
    2017, "D3.1_final-version_POSEIDON_v10.pdf",
    due="Unrelated to provenance",
    display="gutierrez",
    authors="I. Gutierrez, S. Anguita, C. Cortés (TECN), J. van Rooij (JIBE), R. Manzo, B. Intonti, N. Bucello (ACN), P. Silva, R. Casaleiro, M. Curado (UC), M. P. Verzillo, D. Reccia (ELEX)",
    place=Web,
    ID='D31final99:online',
    entrytype='misc',
    howpublished='https://www.poseidon-h2020.eu/wp-content/uploads/2019/08/D3.1_final-version_POSEIDON_v10.pdf',
    month='8',
    category='unrelated',
    backward_steps=1,
))

hadziselimovic2017a = DB(Work(
    2017, "Linked Data Contracts to Support Data Protection and Data Ethics in the Sharing of Scientific Data.",
    due="This approach extends prior ontologies that represent permission and prohibition relationships between agents to make it possible to represent the rights as the GDPR establishes. Although this produces an ontology, it is not relating to the provenance of the activities. In the conclusion section, the authors affirm they intend to integrate the approach with provenance; however, until this review, nothing was published. Additionally, the ontology was not made publicly available in this document.",
    display="hadziselimovic",
    authors="Hadziselimovic, Ensar and Fatema, Kaniz and Pandit, Harshvardhan J and Lewis, Dave",
    place=ISWC,
    ID='hadziselimovic2017linked',
    category='unrelated',
    cluster_id='3362320176505096666',
    entrytype='inproceedings',
    link='https://semsci.github.io/semSci2017/openReview/SemSci_2017_paper_11.pdf',
    pp='55--62',
    scholar='https://scholar.google.com/scholar?cites=3362320176505096666&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='2gm33WJcqS4J',
    scholar_ok=True,
    useful=True,
    not_directly_related_to_provenance=True,
    backward_steps=1,
))

hintze2017a = DB(Work(
    2017, "Meeting upcoming gdpr requirements while maximizing the full value of data analytics",
    due="Unrelated to provenance",
    display="hintze",
    authors="Hintze, Mike and LaFever, Gary",
    place=UnknownConference,
    ID='hintze2017meeting',
    category='unrelated',
    cluster_id='14268935872423729389',
    entrytype='article',
    link='http://files8.design-editor.com/93/9339158/UploadedFiles/1B4F2EF8-BC8D-A12D-C9B1-7DF644A29C1F.pdf',
    scholar='https://scholar.google.com/scholar?cites=14268935872423729389&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='7RilbpNxBcYJ',
    scholar_ok=True,
    backward_steps=1,
))

kirrane2017a = DB(Work(
    2017, "Access control and the resource description framework: A survey",
    due="This paper proposes a survey of the actual access control utilizing the Resource Description Framework (RDF). It is out of the scope of this revision.",
    display="kirrane",
    authors="Kirrane, Sabrina and Mileo, Alessandra and Decker, Stefan",
    place=SemanticWeb,
    ID='kirrane2017access',
    category='unrelated',
    cluster_id='14472180495386884417',
    entrytype='article',
    link='http://www.semantic-web-journal.net/system/files/swj1280.pdf',
    number='2',
    organization='IOS Press',
    pp='311--352',
    scholar='https://scholar.google.com/scholar?cites=14472180495386884417&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='QTnf0HuD18gJ',
    scholar_ok=True,
    volume='8',
    backward_steps=1,
))

knublauch2017a = DB(Work(
    2017, "Shapes Constraint Language (SHACL)",
    due="Unrelated to GDPR",
    display="knublauch",
    authors="Holger Knublauch, TopQuadrant, Inc. Dimitris Kontokostas, University of Leipzig",
    place=Web,
    ID='ShapesCo40:online',
    category='unrelated',
    entrytype='misc',
    month='7',
    scholar_ok='@misc{ShapesCo40:online,\nauthor = {Holger Knublauch, TopQuadrant, Inc. Dimitris Kontokostas, University of Leipzig},\ntitle = {Shapes Constraint Language (SHACL)},\nhowpublished = {https://www.w3.org/TR/shacl/#references},\nmonth = {7},\nyear = {2017},\n}',
    backward_steps=1,
))

neisse2017a = DB(Work(
    2017, "A blockchain-based approach for data accountability and provenance tracking",
    due="This approach does not propose ontologies for representing the provenance of activities ruled by GDPR.",
    display="neisse",
    authors="Neisse, Ricardo and Steri, Gary and Nai-Fovino, Igor",
    place=ARES,
    ID='neisse2017blockchain',
    category='unrelated',
    cluster_id='9079915799371984019',
    entrytype='inproceedings',
    link='https://dl.acm.org/doi/pdf/10.1145/3098954.3098958',
    pp='1--10',
    scholar='https://scholar.google.com.br/scholar?cites=9079915799371984019&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='kywG5E9XAn4J',
    scholar_ok=True,
    start_set=True,
))

nicoletti2017a = DB(Work(
    2017, "PoSeID-on_D2.1-Use-cases-analysis-and-user-scenarios-v1.00.pdf",
    due="Unrelated to provenance",
    authors="Luca Nicoletti (SOGEI), Juan Echevarria Cuenca, Celia Gilsanz (SAN), Carl-Markus Piswanger (BRZ), Erich Forsthuber (BMDW), Alessandra Bagnato (SOFT), Laurent Goncalves (SOFT)",
    place=Web,
    ID='PoSeIDon55:online',
    entrytype='misc',
    howpublished='https://www.poseidon-h2020.eu/wp-content/uploads/2019/08/PoSeID-on_D2.1-Use-cases-analysis-and-user-scenarios-v1.00.pdf',
    month='8',
    category='unrelated',
    backward_steps=1,
))

pandit2017a = DB(Work(
    2017, "Modelling Provenance for GDPR Compliance using Linked Open Data Vocabularies.",
    due="Document not publicly available",
    display="pandit",
    authors="Pandit, Harshvardhan J and Lewis, Dave",
    place=ISWC,
    ID='pandit2017modelling',
    category='nofile',
    cluster_id='https://scholar.google.com/scholar?cites=2287149512924017207&as_sdt=2005&sciodt=0,5&hl=pt-BR',
    entrytype='inproceedings',
    pp='39--40',
    scholar_ok=True,
    backward_steps=1,
))

raschke2017a = DB(Work(
    2017, "Designing a GDPR-compliant and usable privacy dashboard",
    due="Unrelated to provenance",
    display="raschke",
    authors="Raschke, Philip and Küpper, Axel and Drozd, Olha and Kirrane, Sabrina",
    place=IFIP,
    ID='raschke2017designing',
    category='unrelated',
    cluster_id='5388411435758855284',
    entrytype='inproceedings',
    link='https://hal.inria.fr/hal-01883616/file/468319_1_En_14_Chapter.pdf',
    organization='Springer',
    pp='221--236',
    scholar='https://scholar.google.com/scholar?cites=5388411435758855284&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='dCQP3KZ7x0oJ',
    scholar_ok=True,
    backward_steps=1,
))

robaldo2017a = DB(Work(
    2017, "Reified Input/Output logic: Combining Input/Output logic and Reification to represent norms coming from existing legislation",
    due="unrelated to GDPR",
    display="robaldo",
    authors="Robaldo, Livio and Sun, Xin",
    place=JLC,
    ID='robaldo2017reified',
    category='unrelated',
    cluster_id='16193129107564313586',
    entrytype='article',
    link='https://orbilu.uni.lu/bitstream/10993/31378/1/ReifiedIOlogic.pdf',
    number='8',
    organization='Oxford University Press',
    pp='2471--2503',
    scholar='https://scholar.google.com/scholar?cites=16193129107564313586&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='8rto4iCNueAJ',
    scholar_ok=True,
    volume='27',
    backward_steps=1,
))

robol2017a = DB(Work(
    2017, "Toward GDPR-compliant socio-technical systems: modeling language and reasoning framework",
    due="Unrelated to provenance",
    display="robol",
    authors="Robol, Marco and Salnitri, Mattia and Giorgini, Paolo",
    place=IFIP,
    ID='robol2017toward',
    category='unrelated',
    cluster_id='10906410760094714992',
    entrytype='inproceedings',
    link='https://link.springer.com/chapter/10.1007/978-3-319-70241-4_16',
    organization='Springer',
    pp='236--250',
    scholar='https://scholar.google.com/scholar?cites=10906410760094714992&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='cIzxOc1aW5cJ',
    scholar_ok=True,
    backward_steps=1,
))

santos2017a = DB(Work(
    2017, "Detecting and Editing Privacy Policy Pitfalls on the Web.",
    due="Unrelated to provenance",
    display="santos",
    authors="Santos, Cristiana and Gangemi, Aldo and Alam, Mehwish",
    place=JURIX,
    ID='santos2017detecting',
    category='unrelated',
    cluster_id='5180264280713962620',
    entrytype='inproceedings',
    link='https://www.academia.edu/download/58656883/09paper.pdf',
    pp='87--99',
    scholar='https://scholar.google.com/scholar?cites=5180264280713962620&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='fKSZxur-40cJ',
    scholar_ok=True,
    forward_steps=1,
))

schoenen2017a = DB(Work(
    2017, "Using risk patterns to identify violations of data protection policies in cloud systems",
    due="unrelated to GDPR",
    display="schoenen",
    authors="Schoenen, Stefan and Mann, Zoltán Ádám and Metzger, Andreas",
    place=ICSOC,
    ID='schoenen2017using',
    category='unrelated',
    cluster_id='3589847646663395127',
    entrytype='inproceedings',
    link='https://www.researchgate.net/profile/Zoltan-Mann/publication/325787012_Using_Risk_Patterns_to_Identify_Violations_of_Data_Protection_Policies_in_Cloud_Systems/links/5b64cace458515cf1d32f0b5/Using-Risk-Patterns-to-Identify-Violations-of-Data-Protection-Policies-in-Cloud-Systems.pdf',
    organization='Springer',
    pp='296--307',
    scholar='https://scholar.google.com/scholar?cites=3589847646663395127&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='N8ckMWqz0TEJ',
    scholar_ok=True,
    backward_steps=1,
))

silva2017a = DB(Work(
    2017, "D4.3 - RMM 0 PDA - V1.0 - Final",
    due="Unrelated to provenance",
    display="silva",
    authors="Paulo Silva, Rui Casaleiro, Fernando Boavida, Marília Curado, Edmundo Monteiro, Paulo Simões, Nuno Antunes (UC)",
    place=Web,
    ID='D43RMM0P24:online',
    category='unrelated',
    entrytype='misc',
    month='4',
    scholar_ok='@misc{D43RMM0P24:online,\nauthor = {Paulo Silva, Rui Casaleiro, Fernando Boavida, Marília Curado, Edmundo Monteiro, Paulo Simões, Nuno Antunes (UC)},\ntitle = {D4.3 - RMM 0 PDA - V1.0 - Final},\nhowpublished = {https://www.poseidon-h2020.eu/wp-content/uploads/2019/08/D4.3-RMM-and-PDA-V1.0-Final.pdf},\nmonth = {4},\nyear = {2017},\n}',
    backward_steps=1,
))

smes2017a = DB(Work(
    2017, "GDPR Readiness Checklist Template for SMEs",
    due="This document does not propose an approach",
    display="smes",
    authors="Data Protection Commission (DPC)",
    place=Web,
    ID='DPC:Readiness:2017:online',
    category='unrelated',
    entrytype='misc',
    scholar_ok='@misc{DPC:Readiness:2017:online,\nauthor = {GDPR Readiness Checklist Template for SMEs},\ntitle = {Self-Assessment Checklist | Data Protection Commissioner},\nhowpublished = {https://www.dataprotection.ie/en/organisations/resources-organisations/self-assessment-checklist},\nyear = {2017},\n}',
    backward_steps=1,
))

teodoro2017a = DB(Work(
    2017, "D1.1_Initial-List-of-Main-Requirements.pdf",
    due="Unrelated to provenance",
    display="teodoro",
    authors="Douglas Teodoro, Emilie Pasche, Patrick Ruch, Edwin Morley-Fletcher",
    place=Web,
    ID='D11Initi46:online',
    entrytype='misc',
    howpublished='http://www.myhealthmydata.eu/wp-content/themes/Parallax-One/deliverables/D1.1_Initial-List-of-Main-Requirements.pdf',
    month='10',
    category='unrelated',
    backward_steps=1,
))
