# coding: utf-8
from datetime import datetime
from snowballing.models import *
from ..places import *

agarwal2018a = DB(Work(
    2018, "Legislative compliance assessment: framework, model and GDPR instantiation",
    display="agarwal",
    authors="Agarwal, Sushant and Steyskal, Simon and Antunovic, Franjo and Kirrane, Sabrina",
    place=APF,
    ID='agarwal2018legislative',
    category='unrelated',
    summary="The approach proposes a new legislative vocabulary (including new concepts) after demonstrating that the prior legislative vocabulary, Open Digital Rights Language (ODRL) lacks in representing some concepts GDPR makes use. Some of the new concepts are lm:Discretional (for representing non-mandatory obligation, i.e., \"Soft obligation\"), lm:Dispensation (for representing exceptions), lm:Discretional (for representing characteristics or constraints defined in legislation), and ml:Chapter, ml:Article and ml:Paragraph to reference to the legislation text (all under odrl:Policy).\n\nFrom the above, the authors show as a process divided into 5 main steps how to instantiate this model in order to obtain the compliance assessment system. These steps consist of (1) Filter the text related to obligations; (2) Identify interconnections in the text (e.g., which other text this obligation cites?); (3) Normalize the text, which consists in representing the text according to the propose legislative model (since this represents a hard task, they propose boilerplates for expressing obligations in a standard style); (4) Represent the normalized text in a machine-readable format (e.g., using Resource Description Framework); and finally (5) Enhance readability for the users (i.e., append to each obligation extra information in order to make it easy for users checking whether such obligation has been in place; e.g.,  terms definitions as Art. 4, the compliance question related to this obligation).\n\nFinally, the authors compare this approach capabilities against the GDPR compliance tools. In summary, this approach introduces: support for exceptions, where obligation is not applicable; management of evolving law, which ensure updating the obligation accordingly; and, traceability, ensuring changes in the law be easily traced to the corresponding obligations defined for the tool.",
    due="This approach is not directly related to GDPR, lacking to fulfil with IC1. Despite it demonstrates the effectiveness of the approach through the development of a GDPR model and compliance assessment tool, it is related with GDPR secondary",
    cluster_id='5529031943676061063',
    entrytype='inproceedings',
    link='https://epub.wu.ac.at/6487/1/Agarwal-2018-APF.pdf',
    organization='Springer',
    pp='131--149',
    scholar='https://scholar.google.com/scholar?cites=5529031943676061063&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='h2WZOkIRu0wJ',
    scholar_ok=True,
    related="use ORDL, SemanticWeb;\n\naimsTo \"provide a compliance framework tool\";\n\nscope gdprtext:Obligation;\n\nopenIssues \"Apply this approach in all obligations the GDPR proposes in order to get a better evaluation of the approach.\";\n\nprovide \"an extended vocabulary from ORDL that can represent obligations\", LegislativeModel, \"a generic legislative compliance assessment framework to assist the compliance with GDPRobligations\".\n\nORDL is \"a vocabulary used for representing rights expressions\";\n     url https://www.w3.org/TR/odrl-model/\n\nLegislativeModel is \"a vocabulary used for represing obligations expressions\";\n                 introduces lm:Chapter, lm:Article, lm:Paragraph, ml:Feature, lm:Discretional, lm:Dispensation.",
    start_set=True,
    provenance_related=True,
))

alexakis2018a = DB(Work(
    2018, "Business Process Re-engineering and functional toolkit for GDPR compliance",
    due="Not a peer-reviewed document",
    display="alexakis",
    authors="Spiros Alexakis",
    place=Web,
    ID='Business47:online',
    entrytype='misc',
    howpublished='https://www.bpr4gdpr.eu/',
    month='4',
    category='unrelated',
    backward_steps=1,
))

bajaj2018a = DB(Work(
    2018, "4W1H in IoT semantics",
    due="Unrelated to provenance",
    display="bajaj",
    authors="Bajaj, Garvita and Agarwal, Rachit and Singh, Pushpendra and Georgantas, Nikolaos and Issarny, Valérie",
    place=IEEEAccess,
    ID='bajaj20184w1h',
    category='unrelated',
    cluster_id='3772687530796584252',
    entrytype='article',
    link='https://ieeexplore.ieee.org/iel7/6287639/6514899/08509571.pdf',
    organization='IEEE',
    pp='65488--65506',
    scholar='https://scholar.google.com.br/scholar?cites=3772687530796584252&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='PA2tGVJHWzQJ',
    scholar_ok=True,
    volume='6',
    forward_steps=1,
))

bartolini2018a = DB(Work(
    2018, "A legal validation of a formal representation of GDPR articles",
    due="Unrelated to provenance",
    display="bartolini",
    authors="Bartolini, Cesare and Lenzini, Gabriele and Santos, Cristiana",
    place=JURIX,
    ID='bartolini2018legal',
    category='unrelated',
    cluster_id='5471975431326422730',
    entrytype='inproceedings',
    link='http://ceur-ws.org/Vol-2309/10.pdf',
    scholar='https://scholar.google.com/scholar?cites=5471975431326422730&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='ylbgu6lc8EsJ',
    scholar_ok=True,
    backward_steps=1,
))

bartolini2018b = DB(Work(
    2018, "An agile approach to validate a formal representation of the GDPR",
    due="Unrelated to provenance",
    display="bartolini",
    authors="Bartolini, Cesare and Lenzini, Gabriele and Santos, Cristiana",
    place=JSAI,
    ID='bartolini2018agile',
    category='unrelated',
    cluster_id='13701453216308457696',
    entrytype='inproceedings',
    link='https://core.ac.uk/download/pdf/196263660.pdf',
    organization='Springer',
    pp='160--176',
    scholar='https://scholar.google.com/scholar?cites=13701453216308457696&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='4PCyWBtXJb4J',
    scholar_ok=True,
    backward_steps=1,
))

basin2018a = DB(Work(
    2018, "On purpose and by necessity: compliance under the GDPR",
    display="basin",
    authors="Basin, David and Debois, Søren and Hildebrandt, Thomas",
    place=FC,
    ID='basin2018purpose',
    category='unrelated',
    cluster_id='8501187526162782837',
    entrytype='inproceedings',
    link='https://pure.itu.dk/ws/files/84212312/On_Purpose_and_ny_Necessity.pdf',
    organization='Springer',
    pp='20--37',
    scholar='https://scholar.google.com/scholar?cites=8501187526162782837&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='dRrqiQNJ-nUJ',
    scholar_ok=True,
    backward_steps=1,
))

bayle2018a = DB(Work(
    2018, "When blockchain meets the right to be forgotten: technology versus law in the healthcare industry",
    due="Unrelated to provenance",
    display="bayle",
    authors="Bayle, Aurelie and Koscina, Mirko and Manset, David and Perez-Kempner, Octavio",
    place=IEEEWICACM,
    ID='bayle2018blockchain',
    category='unrelated',
    cluster_id='7977619012625257741',
    entrytype='inproceedings',
    link='https://blockhack.osive.com/_downloads/1b4ee9887df64a3f9a0a489c679efc7e/87.pdf',
    organization='IEEE',
    pp='788--792',
    scholar='https://scholar.google.com/scholar?cites=7977619012625257741&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='DVXuiDkytm4J',
    scholar_ok=True,
    backward_steps=1,
))

benfenatki2018a = DB(Work(
    2018, "Towards a User Centric Personal Data Protection Framework",
    due="Unrelated to provenance",
    display="benfenatki",
    authors="Benfenatki, Hind and Biennier, Frédérique and Winckler, Marco and Goncalves, Laurent and Nicolas, Olivier and Saoud, Zohra",
    place=ACMCHI,
    ID='benfenatki2018towards',
    category='unrelated',
    cluster_id='2487546624668131930',
    entrytype='inproceedings',
    link='https://www.researchgate.net/profile/Olivier-Nicolas-2/publication/324919634_Towards_a_User_Centric_Personal_Data_Protection_Framework/links/5aeb2ee5aca2725dabb691fe/Towards-a-User-Centric-Personal-Data-Protection-Framework.pdf',
    pp='6',
    scholar='https://scholar.google.com/scholar?cites=2487546624668131930&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='WuKQvXmKhSIJ',
    scholar_ok=True,
    backward_steps=1,
))

bonatti2018a = DB(Work(
    2018, "The SPECIAL usage policy language",
    due="This approach introduces a usage policy language, which addresses terms and activities to specify a set of authorized operations. The SPECIAL Usage Policy language specifically represents five elements as the minimum core model: the data item, the purpose, the process, the storage, and the recipient. The approach was submitted to scientific publications along with its construction. The ontology is publicly available at https://ai.wu.ac.at/policies/policylanguage/.\n\nSince this document is not a scientific document, it was not tracked by the Google Scholar search engine, and thus it was not possible to roll it in the Snowballing process.",
    display="bonatti",
    authors="Bonatti, PA and Kirrane, S and Petrova, IM and Sauro, L and Schlehahn, E",
    place=Web,
    ID='bonatti2018special',
    category='unrelated',
    entrytype='techreport',
    scholar_ok='@techreport{bonatti2018special,\n  title={The SPECIAL usage policy language},\n  author={Bonatti, PA and Kirrane, S and Petrova, IM and Sauro, L and Schlehahn, E},\n  year={2018},\n  institution={V0. 1. Technical report}\n}',
    link='https://ai.wu.ac.at/policies/policylanguage/',
    backward_steps=1,
))

bonatti2018b = DB(Work(
    2018, "Data privacy vocabularies and controls: Semantic web for transparency and privacy",
    due="This document proposes a privacy ontology to represent the concepts around an application (i.e.,  Innovation Ethics) that can contain personal data. It thus has no relation to GDPR and has been discarded.",
    display="bonatti",
    authors="Bonatti, Piero A and Bos, Bert and Decker, Stefan and Fernández, Javier D and Kirrane, Sabrina and Peristeras, Vassilios and Polleres, Axel and Wenning, Rigo",
    place=SW4SG,
    ID='bonatti2018data',
    category='unrelated',
    cluster_id='14663434318177827862',
    entrytype='inproceedings',
    link='https://openreview.net/pdf?id=98A2Vi9dZO',
    scholar='https://scholar.google.com/scholar?cites=14663434318177827862&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='FvxCetL7fssJ',
    scholar_ok=True,
    backward_steps=1,
))

bonatti2018c = DB(Work(
    2018, "Fast Compliance Checking in an OWL2 Fragment.",
    due="This document does not present a model.",
    display="bonatti",
    authors="Bonatti, Piero A",
    place=IJCAI,
    ID='bonatti2018fast',
    category='unrelated',
    cluster_id='3468769526103133705',
    entrytype='inproceedings',
    link='https://www.ijcai.org/proceedings/2018/0241.pdf',
    pp='1746--1752',
    scholar='https://scholar.google.com/scholar?cites=3468769526103133705&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='Cc4Tc4GLIzAJ',
    scholar_ok=True,
    backward_steps=1,
))

bonatti2018d = DB(Work(
    2018, "The SPECIAL Policy Log Vocabulary",
    due="Discarded due to this document was not made publicly available.",
    display="bonatti",
    authors=" Piero Bonatti, Wouter Dullaert, Javier D. Fernández, Sabrina Kirrane, Milosevic, Axel Polleres ",
    place=Web,
    ID='TheSPECI5:online',
    entrytype='misc',
    howpublished='ttps://ai.wu.ac.at/policies/policylog/',
    month='3',
    category='ok',
    backward_steps=1,
))

debattista2018a = DB(Work(
    2018, "Preface of MEPDaW 2018: Managing the Evolution and Preservation of the Data Web",
    due="Not a peer-reviewed document",
    display="debattista",
    authors="Debattista, Jeremy and Fernández, Javier D and Umbrich, Jürgen and Vidal, Maria-Esther",
    place=MEPDaW,
    ID='debattista2018preface',
    category='unrelated',
    cluster_id='9004688517459312548',
    entrytype='article',
    link='http://ceur-ws.org/Vol-2112/preface-mepdaw-2018.pdf',
    scholar='https://scholar.google.com/scholar?cites=9004688517459312548&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='pH8zbH8U93wJ',
    scholar_ok=True,
    forward_steps=1,
))

debruyne2018a = DB(Work(
    2018, "Generating executable mappings from RDF data cube data structure definitions",
    due="Altough this approach proposses the use of provennce, this focus is not directly related to the GDPR. Additionally, the proposed provenance model is not possible to represent the GDPR concepts.",
    display="debruyne",
    authors="Debruyne, Christophe and Lewis, Dave and O’Sullivan, Declan",
    place=OTM,
    ID='debruyne2018generating',
    category='unrelated',
    cluster_id='4561894562116615271',
    entrytype='inproceedings',
    link='https://drive.google.com/file/d/15Cb-w_97r1VNWxARXDydbw02lIhjk95K/view',
    organization='Springer',
    pp='333--350',
    scholar='https://scholar.google.com.br/scholar?cites=4561894562116615271&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='Zzy_Le8aTz8J',
    scholar_ok=True,
    forward_steps=1,
))

elluri2018a = DB(Work(
    2018, "An integrated knowledge graph to automate gdpr and pci dss compliance",
    due="Although this paper proposes an ontology, this one has no direct relation to data provenance. Additionally, we believe this ontology is too domain-specific and can not contribute to our purposes.\n\nAvailable at: https://mdsoar.org/bitstream/handle/11603/12095/907.pd.pdf#page=4",
    display="elluri",
    authors="Elluri, Lavanya and Nagar, Ankur and Joshi, Karuna Pande",
    place=IEEEBD,
    ID='elluri2018integrated',
    category='unrelated',
    cluster_id='4980289783412402822',
    entrytype='inproceedings',
    link='https://mdsoar.org/bitstream/handle/11603/12095/907.pd.pdf?sequence=1',
    organization='IEEE',
    pp='1266--1271',
    scholar='https://scholar.google.com.br/scholar?cites=4980289783412402822&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='hqrN2iuLHUUJ',
    scholar_ok=True,
    summary='"Big data analytics related to consumer behavior, market analysis, opinions, and recommendation often deal with end user\'s derived and inferred data, along with the observed data. To ensure consumer data protection, rules defined by the European Union\'s General Data Protection Regulation (EU GDPR) must be adhered to by every organization using Personally Identifiable Information (PII) data for Big Data analysis. Similarly, Payment Card Industry Data Security Standard (PCI DSS) has policy guidelines specifically for organizations handling consumer\'s payment card data. Both data regulation policies are currently available only in textual format and require significant manual effort to ensure their compliance. We have developed an integrated, semantically rich Knowledge Graph (or Ontology) to represent the rules mandated by both PCI DSS and EU GDPR. In the Ontology, we have also identified the obligations defined in these regulations and related them with corresponding Cloud Security Alliance (CSA) controls. We have validated this Knowledge Graph against the data policies of major vendors that deal with Big Data. This Knowledge Graph that is available in the public domain can be used by Big Data practitioners to automate data protection compliance in their organization."',
    start_set=True,
))

elluri2018b = DB(Work(
    2018, "A knowledge representation of cloud data controls for EU GDPR compliance",
    due="This ontology proposes classes to represent providers and cloud data consumers' obligations as GDPR elicits. Thus, it is out of the scope of our work.\n\nOntology available at: https://webprotege.stanford.edu/#projects/e8283240-7b78-462f-8e98-0410ef033621/edit/Classes",
    summary="",
    display="elluri",
    authors="Elluri, Lavanya and Joshi, Karuna Pande",
    place=SERVICES,
    ID='elluri2018knowledge',
    category='unrelated',
    cluster_id='6492744007660234660',
    entrytype='inproceedings',
    link='https://mdsoar.org/bitstream/handle/11603/11637/891.pd.pdf?sequence=1&isAllowed=y',
    organization='IEEE',
    pp='45--46',
    scholar='https://scholar.google.com.br/scholar?cites=6492744007660234660&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='pGciYkbcGloJ',
    scholar_ok=True,
    start_set=True,
))

fernández2018a = DB(Work(
    2018, "SPECIAL: Scalable Policy-awarE Linked Data arChitecture for prIvacy, trAnsparency and compLiance",
    due="The paper does not present the provenance model",
    display="fernández",
    authors="Fernández, Javier D and Kirrane, Sabrina and Polleres, Axel and Wenning, Rigo",
    place=Web,
    ID='fernandez2018special',
    category='unrelated',
    cluster_id='10339710340539003344',
    entrytype='article',
    link='http://ceur-ws.org/Vol-2044/paper23/paper23.pdf',
    scholar='https://scholar.google.com/scholar?cites=10339710340539003344&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='0LFCyMUHfo8J',
    scholar_ok=True,
    backward_steps=1,
))

geko2018a = DB(Work(
    2018, "An ontology capturing the interdependence of the general data protection regulation (GDPR) and information security",
    due="In this paper, the authors have developed an ontology-based data protection knowledge graph that shows the relationship between concepts of information security and the GDPR. The proposed ontology identifies five main areas scoped into the GDPR using the recommended process for building ontologies [19]: Data, organization, principles, rights, and obligations.\n\nAdditional to the main relations within these areas, the authors have presented high-level ontology classes and relations, which include Data, Person (Data Subject, Controller, Processor), Data Subject Rights, Organization, Obligation (Controller obligations, Processor obligations, Data Security).\n\nAfter all, the paper explicitly notes that the ontology has not been evaluated and the ontology is not made publicly available. For that reason, we have discarded this publication.\n\nReferences:\n\n[19] Natalya F Noy, Deborah L McGuinness, et al. 2001. Ontology development 101: A guide to creating your first ontology. (2001).",
    display="geko",
    authors="Geko, Melisa and Tjoa, Simon",
    place=CECC,
    ID='geko2018ontology',
    category='unrelated',
    cluster_id='11368800794747960583',
    entrytype='inproceedings',
    link='https://dl.acm.org/doi/pdf/10.1145/3277570.3277590?casa_token=hm7Hl9QsCBIAAAAA:lxOZx60mm76s3ycu-3D72PjuL2vACzmhwXxmjMZ3B1fjdFNvQD7Ws--3GwkMB7VSq4I_CzONBUmOlw',
    pp='1--6',
    scholar='https://scholar.google.com.br/scholar?cites=11368800794747960583&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='B30hnRYYxp0J',
    scholar_ok=True,
    start_set=True,
    useful=True,
    not_directly_related_to_provenance=True,
))

gerl2018a = DB(Work(
    2018, "Critical Analysis of LPL according to Articles 12-14 of the GDPR",
    due="Not directly related to provenance. However, this approach may be useful to our proposes. In this paper, the authors propose improvements for Layered Privacy Language, which intends to model privacy policies to enforce policy-based, from identified requirements of Art. 12 - 14.",
    display="gerl",
    authors="Gerl, Armin and Pohl, Dirk",
    place=ARES,
    ID='gerl2018critical',
    category='unrelated',
    cluster_id='16540057412730955132',
    entrytype='inproceedings',
    link='https://dl.acm.org/doi/pdf/10.1145/3230833.3233267',
    pp='1--9',
    scholar='https://scholar.google.com/scholar?cites=16540057412730955132&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='fCVlepUWiuUJ',
    scholar_ok=True,
    backward_steps=1,
))

gerl2018b = DB(Work(
    2018, "LPL, towards a GDPR-compliant privacy language: formal definition and usage",
    due="Not directly related to provenance. Also, not publicly available.",
    display="gerl",
    authors="Gerl, Armin and Bennani, Nadia and Kosch, Harald and Brunie, Lionel",
    place=Book,
    ID='gerl2018lpl',
    category='unrelated',
    cluster_id='9898574602521560077',
    entrytype='incollection',
    link='https://link.springer.com/chapter/10.1007/978-3-662-57932-9_2',
    organization='Springer',
    pp='41--80',
    scholar='https://scholar.google.com/scholar?cites=9898574602521560077&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='DUQA9ifNXokJ',
    scholar_ok=True,
    backward_steps=1,
))

harkous2018a = DB(Work(
    2018, "Polisis: Automated analysis and presentation of privacy policies using deep learning",
    due="Unrelated to provenance",
    display="harkous",
    authors="Harkous, Hamza and Fawaz, Kassem and Lebret, Rémi and Schaub, Florian and Shin, Kang G and Aberer, Karl",
    place=USENIX,
    ID='harkous2018polisis',
    category='unrelated',
    cluster_id='15062152696096902978',
    entrytype='inproceedings',
    link='https://www.usenix.org/system/files/conference/usenixsecurity18/sec18-harkous.pdf',
    pp='531--548',
    scholar='https://scholar.google.com/scholar?cites=15062152696096902978&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='Qk-MCxOEB9EJ',
    scholar_ok=True,
    backward_steps=1,
))

hoppe2018a = DB(Work(
    2018, "Semantic Applications: Methodology, Technology, Corporate Use",
    due="unrelated to GDPR",
    display="hoppe",
    authors="Hoppe, Thomas and Humm, Bernhard and Reibold, Anatol",
    place=Book,
    ID='hoppe2018semantic',
    category='unrelated',
    cluster_id='6399425056473132056',
    entrytype='book',
    link='https://link.springer.com/content/pdf/10.1007/978-3-662-55433-3.pdf',
    organization='Springer',
    scholar='https://scholar.google.com/scholar?cites=6399425056473132056&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='GKzQ6S5Tz1gJ',
    scholar_ok=True,
    backward_steps=1,
))

kirrane2018a = DB(Work(
    2018, "A scalable consent, transparency and compliance architecture",
    due="Although the approach this document introduces presents a model where components are capable of representing the provenance of the activities related to GDPR, in this document, specifically, this model is not introduced. Thus, we consider this document unrelated.",
    display="kirrane",
    authors="Kirrane, Sabrina and Fernández, Javier D and Dullaert, Wouter and Milosevic, Uros and Polleres, Axel and Bonatti, Piero A and Wenning, Rigo and Drozd, Olha and Raschke, Philip",
    place=ESWC,
    ID='kirrane2018scalable',
    category='ok',
    entrytype='inproceedings',
    organization='Springer',
    pp='131--136',
    scholar="https://scholar.google.com/scholar?cites=13808115522786291090&as_sdt=2005&sciodt=0,5&hl=pt-BR",
    scholar_ok="@inproceedings{kirrane2018scalable,\n  title={A scalable consent, transparency and compliance architecture},\n  author={Kirrane, Sabrina and Fern{\\'a}ndez, Javier D and Dullaert, Wouter and Milosevic, Uros and Polleres, Axel and Bonatti, Piero A and Wenning, Rigo and Drozd, Olha and Raschke, Philip},\n  booktitle={European Semantic Web Conference},\n  pages={131--136},\n  year={2018},\n  organization={Springer}\n}",
    link='https://epub.wu.ac.at/6483/1/ESWC2018.pdf',
    backward_steps=1,
))

kirrane2018b = DB(Work(
    2018, "Privacy, security and policies: A review of problems and solutions with semantic web technologies",
    due="unrelated to GDPR",
    display="kirrane",
    authors="Kirrane, Sabrina and Villata, Serena and d’Aquin, Mathieu",
    place=SemanticWeb,
    ID='kirrane2018privacy',
    category='unrelated',
    cluster_id='13372119830118833140',
    entrytype='article',
    link='https://content.iospress.com/articles/semantic-web/sw289',
    number='2',
    organization='IOS Press',
    pp='153--161',
    scholar='https://scholar.google.com.br/scholar?cites=13372119830118833140&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='9JswECNQk7kJ',
    scholar_ok=True,
    volume='9',
    forward_steps=1,
))

legislature2018a = DB(Work(
    2018, "Bill Text - AB-375 Privacy: personal information: businesses.",
    due="Unrelated to GDPR",
    display="legislature",
    authors="California State Legislature",
    place=Web,
    ID='BillText48:online',
    entrytype='misc',
    howpublished='https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201720180AB375',
    month='6',
    category='unrelated',
    backward_steps=1,
))

leone2018a = DB(Work(
    2018, "Legal Ontologies and How to Choose Them: the InvestigatiOnt Tool.",
    due="unrelated to GDPR",
    display="leone",
    authors="Leone, Valentina and Di Caro, Luigi and Villata, Serena",
    place=ISWC,
    ID='leone2018legal',
    category='unrelated',
    cluster_id='10207200821872976075',
    entrytype='inproceedings',
    link='https://cris.unibo.it/bitstream/11585/800734/1/2018-05-ISWC2018-demo_legal_ontologies.pdf',
    scholar='https://scholar.google.com/scholar?cites=10207200821872976075&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='y2DQQhFDp40J',
    scholar_ok=True,
    backward_steps=1,
))

linden2018a = DB(Work(
    2018, "The privacy policy landscape after the GDPR",
    due="Not a peer-reviewed document",
    display="linden",
    authors="Linden, Thomas and Khandelwal, Rishabh and Harkous, Hamza and Fawaz, Kassem",
    place=arXiv,
    ID='linden2018privacy',
    category='unrelated',
    cluster_id='10903818614295614322',
    entrytype='article',
    link='https://arxiv.org/pdf/1809.08396',
    scholar='https://scholar.google.com/scholar?cites=10903818614295614322&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='ctNhQEIlUpcJ',
    scholar_ok=True,
    backward_steps=1,
))

lodge2018a = DB(Work(
    2018, "Developing GDPR compliant apps for the edge",
    due="unrelated to GDPR",
    display="lodge",
    authors="Lodge, Tom and Crabtree, Andy and Brown, Anthony",
    place=DPM,
    ID='lodge2018developing',
    category='unrelated',
    cluster_id='16804874008932169779',
    entrytype='incollection',
    link='https://nottingham-repository.worktribe.com/preview/1158928/paper7.pdf',
    organization='Springer',
    pp='313--328',
    scholar='https://scholar.google.com/scholar?cites=16804874008932169779&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='M7iYBeDnNukJ',
    scholar_ok=True,
    backward_steps=1,
))

marini2018a = DB(Work(
    2018, "GDPR_CCPA_Comparison-Guide.pdf",
    due="This document aims to presenta a comparison between the GDPR and the CCPA (Californian privacy law). Thus, it out of the scope",
    display="marini",
    authors="Alice Marini, Alexis Kateifides, Joel Bates",
    place=Web,
    ID='GDPRCCPA82:online',
    category='unrelated',
    entrytype='misc',
    month='11',
    scholar_ok='@misc{GDPRCCPA82:online,\nauthor = {Alice Marini, Alexis Kateifides, Joel Bates},\ntitle = {GDPR\\_CCPA\\_Comparison-Guide.pdf},\nhowpublished = {https://fpf.org/wp-content/uploads/2018/11/GDPR_CCPA_Comparison-Guide.pdf},\nmonth = {11},\nyear = {2018},\n}',
    backward_steps=1,
))

meis2018a = DB(Work(
    2018, "Problem-Based Privacy Analysis (ProPAn): A Computer-aided Privacy Requirements Engineering Method",
    due="FIle not found",
    display="meis",
    authors="Meis, Rene",
    place=Book,
    ID='meis2018problem',
    category='nofile',
    cluster_id='6400880598428508268',
    entrytype='book',
    link='https://search.proquest.com/openview/41680eecdfbf3298929a778039d0e225/1?pq-origsite=gscholar&cbl=2026366&diss=y',
    organization='Universitaet Duisburg-Essen (Germany)',
    scholar='https://scholar.google.com/scholar?cites=6400880598428508268&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='bGAFr_1-1FgJ',
    scholar_ok=True,
    forward_steps=1,
))

oltramari2018a = DB(Work(
    2018, "PrivOnto: A semantic framework for the analysis of privacy policies",
    due="PrivOnto's ontology is focused on annotating privacy policy documents. Thus, it is out of our scope. Additionally, it has no direct relation to GDPR.",
    display="oltramari",
    authors="Oltramari, Alessandro and Piraviperumal, Dhivya and Schaub, Florian and Wilson, Shomir and Cherivirala, Sushain and Norton, Thomas B and Russell, N Cameron and Story, Peter and Reidenberg, Joel and Sadeh, Norman",
    place=Web,
    ID='oltramari2018privonto',
    category='unrelated',
    entrytype='article',
    number='2',
    organization='IOS Press',
    pp='185--203',
    scholar='https://scholar.google.com/scholar?cites=17738929873691880874&as_sdt=2005&sciodt=0,5&hl=pt-BR',
    scholar_ok='@article{oltramari2018privonto,\n  title={PrivOnto: A semantic framework for the analysis of privacy policies},\n  author={Oltramari, Alessandro and Piraviperumal, Dhivya and Schaub, Florian and Wilson, Shomir and Cherivirala, Sushain and Norton, Thomas B and Russell, N Cameron and Story, Peter and Reidenberg, Joel and Sadeh, Norman},\n  journal={Semantic Web},\n  volume={9},\n  number={2},\n  pages={185--203},\n  year={2018},\n  publisher={IOS Press}\n}\n',
    volume='9',
    link='http://www.semantic-web-journal.net/system/files/swj1597.pdf',
    backward_steps=1,
))

palm2018a = DB(Work(
    2018, "Modeling data protection vulnerabilities of cloud systems using risk patterns",
    due="unrelated to GDPR",
    display="palm",
    authors="Palm, Alexander and Mann, Zoltán Ádám and Metzger, Andreas",
    place=SAM,
    ID='palm2018modeling',
    category='unrelated',
    cluster_id='2413390393886087026',
    entrytype='inproceedings',
    link='http://cs.bme.hu/~manusz/publications/SAM-2018/Palm_Mann_Metzger_SAM_2018.pdf',
    organization='Springer',
    pp='1--19',
    scholar='https://scholar.google.com/scholar?cites=2413390393886087026&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='cpfry8YVfiEJ',
    scholar_ok=True,
    backward_steps=1,
))

palmirani2018a = DB(Work(
    2018, "Legal ontology for modelling GDPR concepts and norms",
    due="Unrelated to provenance. This paper introduces a privacy vocabulary to represent and model concepts of the GDPR. This ontology is presented in a few modules that aim to represent specific topics of the law, namely: (1) Data and Document, (2) Agent and Role, (3) Purposes and Legal Basis, (4) Data Processing, (5) Deontic Operators, (6) Rights and Obligations relationships, (7) Duties and Violation. This ontology evaluation is presented in running European H2020 Projects.",
    display="palmirani",
    authors="Palmirani, Monica and Martoni, Michele and Rossi, Arianna and Bartolini, Cesare and Robaldo, Livio",
    place=JURIX,
    ID='palmirani2018legal',
    category='unrelated',
    cluster_id='15173068655589741090',
    entrytype='incollection',
    link='https://ebooks.iospress.nl/pdf/doi/10.3233/978-1-61499-935-5-91',
    organization='IOS Press',
    pp='91--100',
    scholar='https://scholar.google.com.br/scholar?cites=15173068655589741090&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='IlIKSY2RkdIJ',
    scholar_ok=True,
    summary="This paper introduces PrOnto, an ontology that models GDPR concepts to support legal reasoning and compliance checking by extending LegalRuleML, which allows the synchronization of the legal rule language modelling with the ontology. The main feature of PrOnto is allowing models of deontic operators as predicates such as rights, obligations, permission and prohibition. The paper does not explain how exactly those predicates take place and should be used; however, it seems to be clear that those are instantiated by the creation of RDF triples. The paper lacks examples of how such an approach might be instantiated in real use-cases.\n\nAdditionally, PrOnto allows the modelling of the plan that describes how something should be laid out and the concrete sequence of actions that were actually performed. Such features are important to represent the Impact Assessment Plan.",
    start_set=True,
))

palmirani2018b = DB(Work(
    2018, "Pronto: Privacy ontology for legal reasoning",
    due="File not found",
    display="palmirani",
    authors="Palmirani, Monica and Martoni, Michele and Rossi, Arianna and Bartolini, Cesare and Robaldo, Livio",
    place=EGOVIS,
    ID='palmirani2018pronto',
    category='nofile',
    cluster_id='3562507409853355273',
    entrytype='inproceedings',
    link='https://cris.unibo.it/retrieve/handle/11585/648022/519515/POST%20PRINT%20PrOntoPrivacyOntologyForLegalReasoning.pdf',
    organization='Springer',
    pp='139--152',
    scholar='https://scholar.google.com.br/scholar?cites=3562507409853355273&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='CZUBQp2RcDEJ',
    scholar_ok=True,
    summary='"The GDPR (GDPR, REGULATION (EU) 2016/679 OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL of 27 April 2016 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC (General Data Protection Regulation)) introduces the self-assessment of digital risks and the modulation of duties on the basis of the impact assessment analysis, including specific measures that intend to safeguard the data subject’s human dignity and fundamental rights. Semantic web technologies and legal reasoning tools can support privacy-by-default and legal compliance. In this light, this paper presents a first draft of a legal ontology on the GDPR, called PrOnto, that has the goal of providing a legal knowledge modelling of the privacy agents, data types, types of processing operations, rights and obligations. The methodology used here is based on legal theory analysis joined with ontological patterns."',
    backward_steps=1,
))

palmirani2018c = DB(Work(
    2018, "Pronto: Privacy ontology for legal compliance",
    due="This paper introduces a privacy ontology to represent and model concepts of the GDPR. This ontology is presented in a few modules which aim to represent specific topics of the law, namely: (1) Data and Document, (2) Agent and Role, (3) Purposes and Legal Basis, (4) Data Processing, (5) Deontic Operators, (6) Rights and Obligations relationships, (7) Duties and Violation. This ontology evaluation is presented in running European H2020 Projects. Although some of these modules can assist in the objective of our research, this paper does not make publicly available this ontology.",
    display="palmirani",
    authors="Palmirani, Monica and Martoni, Michele and Rossi, Arianna and Bartolini, Cesare and Robaldo, Livio",
    place=ECDG,
    ID='palmirani2018pronto',
    category='urelated',
    cluster_id='5106793140656302002',
    entrytype='inproceedings',
    link='https://www.academia.edu/download/76627164/Palmirani_20et_20al_20050.pdf',
    pp='142--151',
    scholar='https://scholar.google.com.br/scholar?cites=5106793140656302002&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='smc48k353kYJ',
    scholar_ok=True,
    start_set=True,
))

palmirani2018d = DB(Work(
    2018, "Modelling Legal Knowledge for GDPR Compliance Checking.",
    due="Unrelated due to not proposing a new ontology. Actually, this approach consists in presenting a framework as a proof-of-concept reutilizing prior approaches (e.g., PrOnto, LegalRuleML, etc) to support legal reasoning and compliance checking.",
    display="palmirani",
    authors="Palmirani, Monica and Governatori, Guido",
    place=JURIX,
    ID='palmirani2018modelling',
    category='unrelated',
    cluster_id='13463151051009303660',
    entrytype='inproceedings',
    link='https://ebooks.iospress.nl/pdf/doi/10.3233/978-1-61499-935-5-101',
    pp='101--110',
    scholar='https://scholar.google.com.br/scholar?cites=13463151051009303660&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='bCTW0Iy41roJ',
    scholar_ok=True,
    volume='313',
    start_set=True,
))

pandit2018a = DB(Work(
    2018, "Queryable provenance metadata for GDPR compliance",
    display="pandit (Querying semantic web technology)",
    authors="Pandit, Harshvardhan J and O’Sullivan, Declan and Lewis, Dave",
    place=SEMANTiCS,
    ID='pandit2018queryable',
    cluster_id='807402735392335088',
    entrytype='article',
    link='https://www.sciencedirect.com/science/article/pii/S1877050918316314/pdf?md5=82e3fdbfd7f1f65c49bd364573f59a39&pid=1-s2.0-S1877050918316314-main.pdf',
    organization='Elsevier',
    pp='262--268',
    scholar='https://scholar.google.com/scholar?cites=807402735392335088&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='8CS9kYJ4NAsJ',
    scholar_ok=True,
    volume='137',
    related="use SemanticWeb;\n\nprovide \"a proof-of-concept demonstrating the effectiveness using of semantic web technologies for automating the retrieval of information related to the GDPR compliance questions elicited in the GDPR readiness checklist published by Ireland's Data Protection Commissioner's office\";\n\naimsTo \"demonstrate querying of information related to a document questions (i.e., the GDPR readiness checklist published by Ireland's Data Protection Commissioner's office) using semantic web technologies\";\n\nscope \"all the law\";\n\npotentialApplications \"Automating Compliance Checking\", \"Documenting GDPR compliance\", \"Impact Assessments, Continuous Evaluations\", \"Subject Access Request\";\n\nrelatedWork SPECIAL, ImpactAssessment, Ontologies, Visualisation, SmartContracts, KnowledgeGraphs, AccessControl;\n\nopenIssues \"expanding this semantic web based approach towards the representation and incorporation of five information categories, which are provenance, data sharing agreements, consent, certification, and compliance\", \"creating a knowledge-based system for GDPR compliance\".",
    summary="This work presents a proof-of-concept demonstrating the use of semantic web technologies to address GDPR compliance obligations. This demonstration takes place by modelling the GDPR readiness checklist published by Ireland's Data Protection Commissioner's office as an authoritative document into prior published ontologies after it is mapped use-cases in SPARQL queries for automating the retrieval of information related to these queries.",
    due="This paper does not present a data provenance model, instead it presents how utilizing such technologies can assists in representation and querying compliance information to GDPR.",
    category='unrelated',
    start_set=True,
    provenance_related=True,
))

pandit2018b = DB(Work(
    2018, "Exploring GDPR Compliance Over Provenance Graphs Using SHACL.",
    due="This paper does not present a model for the GDPR. However, it might be helpful due to the advanced usage of any model. In the previous work, the authors proposed a model to represent the activities related to the GDPR and demonstrate the use of semantic web technologies to allow querying compliance-related information by describing them using SPARQL. However, in this publication, no model has been introduced.",
    display="pandit",
    authors="Pandit, Harshvardhan Jitendra and O'Sullivan, Declan and Lewis, Dave",
    place=SEMANTiCS,
    ID='pandit2018exploring',
    category='unrelated',
    cluster_id='13838446894479759828',
    entrytype='inproceedings',
    link='http://www.tara.tcd.ie/bitstream/handle/2262/91542/SEMANTiCS2018___Poster___Exploring_GDPR_Compliance_Over_Provenance_Graphs_Using_SHACL.pdf?sequence=1',
    scholar='https://scholar.google.com.br/scholar?cites=13838446894479759828&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='1NmSnCEKDMAJ',
    scholar_ok=True,
    summary='"Semantic web technologies provide an open and adaptable framework for compliance regarding the General Data Protection Regulation (GDPR). Our previous work in this regard demonstrates the use of SPARQL for querying provenance of consent and personal data lifecycles for compliance. We extend this work through our model for evaluation of GDPR compliance using SHACL to validate the correctness and completeness of information. The model describes the creation of a compliance graph consisting of information required to document and demonstrate compliance linked to specific articles and obligations within the GDPR using the GDPRtEXT vocabulary."',
    start_set=True,
))

pandit2018c = DB(Work(
    2018, "An Ontology Design Pattern for Describing Personal Data in Privacy Policies.",
    due="This paper uses prior ontologies to meet GDPR issues related to policy privacy.",
    display="pandit",
    authors="Pandit, Harshvardhan J and O'Sullivan, Declan and Lewis, Dave",
    place=ISWC,
    ID='pandit2018ontology',
    category='unrelated',
    cluster_id='3977968111681383220',
    entrytype='inproceedings',
    link='http://ceur-ws.org/Vol-2195/pattern_paper_3.pdf',
    pp='29--39',
    scholar='https://scholar.google.com.br/scholar?cites=3977968111681383220&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='NKuZ4OuUNDcJ',
    scholar_ok=True,
    start_set=True,
))

pandit2018d = DB(Work(
    2018, "Towards Knowledge-Based Systems for GDPR Compliance.",
    due="This paper does not introduce a new ontology, but it reuses prior ones to propose a knowledge-based system. It can be helpful for future work addressing practical concerns.",
    display="pandit",
    authors="Pandit, Harshvardhan Jitendra and O'Sullivan, Declan and Lewis, Dave",
    place=ISWC,
    ID='pandit2018towards',
    category='unrelated',
    cluster_id='5758490859776445787',
    entrytype='inproceedings',
    link='http://www.tara.tcd.ie/bitstream/handle/2262/91663/Towards_Knowledge_Based_Systems_for_GDPR_Compliance.pdf?sequence=1',
    scholar='https://scholar.google.com.br/scholar?cites=5758490859776445787&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='Ww1PW-1E6k8J',
    scholar_ok=True,
    start_set=True,
))

pandit2018e = DB(Work(
    2018, "GDPRtEXT-GDPR as a linked data resource",
    due="The introduced ontology aims to represent concepts of the GDPR. This goal is out of the scope of our work.",
    display="pandit",
    authors="Pandit, Harshvardhan J and Fatema, Kaniz and O’Sullivan, Declan and Lewis, Dave",
    place=ESWC,
    ID='pandit2018gdprtext',
    category='unrelated',
    cluster_id='2776106745007214232',
    entrytype='inproceedings',
    link='https://openscience.adaptcentre.ie/pb/GDPRtEXT.pdf',
    organization='Springer',
    pp='481--495',
    scholar='https://scholar.google.com.br/scholar?cites=2776106745007214232&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='mI64SmC2hiYJ',
    scholar_ok=True,
    start_set=True,
))

pandit2018f = DB(Work(
    2018, "GDPR-driven Change Detection in Consent and Activity Metadata",
    due="This paper discuss the use of representation and collection of data provenance of consent and activities as a manner to support GDPR compliance",
    display="pandit",
    authors="Pandit, Harshvardhan J and O’Sullivan, Declan and Lewis, Dave",
    place=MEPDaW,
    ID='pandit2018gdpr',
    category='ok',
    cluster_id='7912749283467561322',
    entrytype='inproceedings',
    link='http://www.tara.tcd.ie/bitstream/handle/2262/91562/ESWC2018___MEPDaW___GDPR_driven_Change_Detection_in_Consent_and_Activity_Metadata.pdf?sequence=1',
    pp='5',
    scholar='https://scholar.google.com/scholar?cites=7912749283467561322&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='aonPvYy7z20J',
    scholar_ok=True,
    volume='4',
    backward_steps=1,
))

pandit2018g = DB(Work(
    2018, "Extracting provenance metadata from privacy policies",
    due="In this paper, the authors demonstrate how prior provenance models they have proposed can assist in extracting, identifying, and representing provenance information within privacy policies.",
    display="pandit",
    authors="Pandit, Harshvardhan Jitendra and O’Sullivan, Declan and Lewis, Dave",
    place=IPAW,
    ID='pandit2018extracting',
    category='ok',
    cluster_id='10369772620433056988',
    entrytype='inproceedings',
    link='http://www.tara.tcd.ie/bitstream/handle/2262/91556/IPAW2018___Extracting_Provenance_Metadata_from_Privacy_Policies.pdf?sequence=1',
    organization='Springer',
    pp='262--265',
    scholar='https://scholar.google.com/scholar?cites=10369772620433056988&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='3OR7wkHV6I8J',
    scholar_ok=True,
    backward_steps=1,
))

pandit2018h = DB(Work(
    2018, "Personalised Privacy Policies",
    due="Unrelated to provenance",
    display="pandit",
    authors="Pandit, Harshvardhan Jitendra and O’Sullivan, Declan and Lewis, Dave",
    place=ADBIS,
    ID='pandit2018personalised',
    category='unrelated',
    cluster_id='9375529669658679700',
    entrytype='inproceedings',
    link='http://www.tara.tcd.ie/bitstream/handle/2262/91558/TELERISE2018___Personalised_Privacy_Policies.pdf?sequence=1',
    organization='Springer',
    pp='127--137',
    scholar='https://scholar.google.com/scholar?cites=9375529669658679700&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='lBkklY-SHIIJ',
    scholar_ok=True,
    backward_steps=1,
))

pandit2018i = DB(Work(
    2018, "An exploration of data interoperability for GDPR",
    due="FIle not found",
    display="pandit",
    authors="Pandit, Harshvardhan J and Debruyne, Christophe and O'Sullivan, Declan and Lewis, Dave",
    place=IJSR,
    ID='pandit2018exploration',
    category='nofile',
    cluster_id='7915380995713292856',
    entrytype='article',
    link='https://www.igi-global.com/article/an-exploration-of-data-interoperability-for-gdpr/218518',
    number='1',
    organization='IGI Global',
    pp='1--21',
    scholar='https://scholar.google.com/scholar?cites=7915380995713292856&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='OFpe_xMV2W0J',
    scholar_ok=True,
    volume='16',
    backward_steps=1,
))

pandit2018j = DB(Work(
    2018, "GDPR data interoperability model",
    due="This approach does not propose a provenance model. Before, it concerns preparing the grounds for a commonality between terms used in further models. It was done by exploring the information flows influenced by the GDPR, which led to identifying entities involved in such flows and their relations. The methodology employed considers an analysis of the relevant articles for each entity. Thus, we think this paper is out of our scope.",
    display="pandit",
    authors="Pandit, Harshvardhan J and O’Sullivan, Declan and Lewis, Dave",
    place=EURAS,
    ID='pandit2018gdpr',
    category='unrelated',
    cluster_id='8372456580722802551',
    entrytype='inproceedings',
    link='http://www.tara.tcd.ie/bitstream/handle/2262/91569/2018_conference_GDPR_data_interoperability_model.pdf?sequence=1',
    scholar='https://scholar.google.com.br/scholar?cites=8372456580722802551&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='dz9dp-bwMHQJ',
    scholar_ok=True,
    forward_steps=1,
))

pandit2018k = DB(Work(
    2018, "An Exploration of the Data Interoperability Model for GDPR",
    due="This paper models the data exchange between different entities related to the GDPR. It does not directly relate to the purposes of our work; hence, we have considered it out of our scope. However, it may provide some insights at the time of extending our model.",
    display="pandit",
    authors="Pandit, Harshvardhan J and Debruyne, Christophe and O’Sullivan, Declan and Lewis, Dave",
    place=IJSR,
    ID='panditexploration',
    category='unrelated',
    cluster_id='1917032435182051083',
    entrytype='article',
    link='https://chrdebru.github.io/papers/2018-ijsr-preprint.pdf',
    scholar='https://scholar.google.com.br/scholar?cites=1917032435182051083&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='C5_tydeqmhoJ',
    scholar_ok=True,
    forward_steps=1,
))

pasquier2018a = DB(Work(
    2018, "Data provenance to audit compliance with privacy policy in the Internet of Things",
    due="unrelated to GDPR",
    display="pasquier",
    authors="Pasquier, Thomas and Singh, Jatinder and Powles, Julia and Eyers, David and Seltzer, Margo and Bacon, Jean",
    place=PUC,
    ID='pasquier2018data',
    category='unrelated',
    cluster_id='7033276659499125046',
    entrytype='article',
    link='https://dash.harvard.edu/bitstream/handle/1/35350573/ubi-2017.pdf?sequence=1',
    number='2',
    organization='Springer',
    pp='333--344',
    scholar='https://scholar.google.com/scholar?cites=7033276659499125046&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='Nsl9oNs3m2EJ',
    scholar_ok=True,
    volume='22',
    backward_steps=1,
))

pellegrini2018a = DB(Work(
    2018, "A genealogy and classification of rights expression languages-preliminary results",
    due="This paper present a review of the literature concerning to Rights Expression Languages (REL). Unrelated to GDPR and provenance",
    display="pellegrini",
    authors="Pellegrini, Tassilo and Schönhofer, Andrea and Kirrane, Sabrina and Steyskal, Simon and Fensel, Anna and Panasiuk, Oleksandra and Mireles-Chavez, Victor and Thurner, Thomas and Dörfler, Markus and Polleres, Axel",
    place=IRIS,
    ID='pellegrini2018genealogy',
    category='unrelated',
    cluster_id='17365163437634396439',
    entrytype='inproceedings',
    link='https://www.researchgate.net/profile/Anna-Fensel/publication/330799134_A_GENEALOGY_AND_CLASSIFICATION_OF_RIGHTS_EXPRESSION_LANGUAGES-PRELIMINARY_RESULTS/links/5c54793f92851c22a3a132df/A-GENEALOGY-AND-CLASSIFICATION-OF-RIGHTS-EXPRESSION-LANGUAGES-PRELIMINARY-RESULTS.pdf',
    pp='243--250',
    scholar='https://scholar.google.com/scholar?cites=17365163437634396439&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='F6HMViR0_fAJ',
    scholar_ok=True,
    backward_steps=1,
))

peras2018a = DB(Work(
    2018, "Guidelines for GDPR compliant consent and data management model in ICT businesses",
    due="This paper do not propose a provenace model propose",
    display="peras",
    authors="Peras, Dijana",
    place=CECIIS,
    ID='peras2018guidelines',
    category='unrelated',
    cluster_id='5729905734549014800',
    entrytype='inproceedings',
    link='https://www.bib.irb.hr/980604/download/980604.ETICT-3.pdf',
    organization='Faculty of Organization and Informatics Varazdin',
    pp='113--121',
    scholar='https://scholar.google.com/scholar?cites=5729905734549014800&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='EIlEQOi2hE8J',
    scholar_ok=True,
    backward_steps=1,
))

politou2018a = DB(Work(
    2018, "Forgetting personal data and revoking consent under the GDPR: Challenges and proposed solutions",
    due="Unrelated to provenance",
    display="politou",
    authors="Politou, Eugenia and Alepis, Efthimios and Patsakis, Constantinos",
    place=JoC,
    ID='politou2018forgetting',
    category='unrelated',
    cluster_id='1495326122069771887',
    entrytype='article',
    link='https://academic.oup.com/cybersecurity/article-pdf/4/1/tyy001/27126900/tyy001.pdf',
    number='1',
    organization='Oxford University Press',
    pp='tyy001',
    scholar='https://scholar.google.com/scholar?cites=1495326122069771887&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='b8ZUeS93wBQJ',
    scholar_ok=True,
    volume='4',
    backward_steps=1,
))

rantos2018a = DB(Work(
    2018, "ADvoCATE: a consent management platform for personal data processing in the IoT using blockchain technology",
    due="Unrelated to provenance",
    display="rantos",
    authors="Rantos, Konstantinos and Drosatos, George and Demertzis, Konstantinos and Ilioudis, Christos and Papanikolaou, Alexandros and Kritsas, Antonios",
    place=SecITC,
    ID='rantos2018advocate',
    category='unrelated',
    cluster_id='12251278288284526880',
    entrytype='inproceedings',
    link='https://www.academia.edu/download/63289089/secitc2018-advocate-consent_fin20200512-86045-feadb1.pdf',
    organization='Springer',
    pp='300--313',
    scholar='https://scholar.google.com/scholar?cites=12251278288284526880&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='IKmncbFIBaoJ',
    scholar_ok=True,
    backward_steps=1,
))

rantos2018b = DB(Work(
    2018, "Blockchain-based Consents Management for Personal Data Processing in the IoT Ecosystem.",
    due="unrelated to GDPR",
    display="rantos",
    authors="Rantos, Konstantinos and Drosatos, George and Demertzis, Konstantinos and Ilioudis, Christos and Papanikolaou, Alexandros",
    place=ICETE,
    ID='rantos2018blockchain',
    category='unrelated',
    cluster_id='12445251332780108175',
    entrytype='article',
    link='http://utopia.duth.gr/~kdemertz/papers/SECRYPT.pdf',
    scholar='https://scholar.google.com/scholar?cites=12445251332780108175&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='j6nQPiZqtqwJ',
    scholar_ok=True,
    volume='298',
    forward_steps=1,
))

teruel2018a = DB(Work(
    2018, "Legal text processing within the MIREL project",
    due="This document proposes a tool and the resources to mine and reason legal texts. It thus has no direct relation to provenance. Additionally, the authors have not directly applicated this approach to GDPR requirements.",
    display="MIREL",
    authors="Teruel, Milagro and Cardellino, Cristian and Cardellino, Fernando and Alemany, Laura Alonso and Villata, Serena",
    place=LREC,
    ID='teruel2018legal',
    category='unrelated',
    cluster_id='8367665969725860821',
    entrytype='inproceedings',
    link='http://www.cosasbuenas.es/pdf/2018.legalkg.pdf#page=49',
    pp='42',
    scholar='https://scholar.google.com/scholar?cites=8367665969725860821&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='1WuinN3rH3QJ',
    scholar_ok=True,
    backward_steps=1,
))

tesfay2018a = DB(Work(
    2018, "PrivacyGuide: towards an implementation of the EU GDPR on internet privacy policy evaluation",
    due="Unrelated to provenance",
    display="tesfay",
    authors="Tesfay, Welderufael B and Hofmann, Peter and Nakamura, Toru and Kiyomoto, Shinsaku and Serna, Jetzabel",
    place=CODSPAY,
    ID='tesfay2018privacyguide',
    category='unrelated',
    cluster_id='6945571144178280258',
    entrytype='inproceedings',
    link='https://dl.acm.org/doi/pdf/10.1145/3180445.3180447?casa_token=V2Vr27heBhMAAAAA:cmLCwvnDpagDMu_ojqsCQIWRMck6Nk9jgDIMz-F6THKwaJX0BYQLx9CGJ8kuvR0mHze_XpL7kGsvOQ',
    pp='15--21',
    scholar='https://scholar.google.com/scholar?cites=6945571144178280258&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='QifzCiigY2AJ',
    scholar_ok=True,
    backward_steps=1,
))

tom2018a = DB(Work(
    2018, "Conceptual representation of the GDPR: model and application directions",
    due="Although this approach proposes concepts for resenting the GDPR, it is not related to provenance.",
    display="tom",
    authors="Tom, Jake and Sing, Eduard and Matulevicius, Raimundas",
    place=BIR,
    ID='tom2018conceptual',
    cluster_id='11236335810691020005',
    entrytype='inproceedings',
    link='https://www.researchgate.net/profile/Jake-Tom/publication/327232074_Conceptual_Representation_of_the_GDPR_Model_and_Application_Directions_17th_International_Conference_BIR_2018_Stockholm_Sweden_September_24-26_2018_Proceedings/links/5c87f58292851c1df93d3d2a/Conceptual-Representation-of-the-GDPR-Model-and-Application-Directions-17th-International-Conference-BIR-2018-Stockholm-Sweden-September-24-26-2018-Proceedings.pdf',
    organization='Springer',
    pp='18--28',
    scholar='https://scholar.google.com/scholar?cites=11236335810691020005&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='5TQ9HeN775sJ',
    scholar_ok=True,
    related="Representation",
    category="ok",
    backward_steps=1,
))

singh2018a = DB(Work(
    2018, "Decision provenance: Harnessing data flow for accountable systems",
    due="This approach does not introduce a new ontology or model to assists in GDPR issues.",
    display="singh ✔️",
    authors="Singh, Jatinder and Cobbe, Jennifer and Norval, Chris",
    place=IEEEAccess,
    ID='singh2018decision',
    category='unrelated',
    cluster_id='14024850405532853821',
    entrytype='article',
    link='https://ieeexplore.ieee.org/iel7/6287639/8600701/08579125.pdf',
    organization='IEEE',
    pp='6562--6574',
    scholar='https://scholar.google.com/scholar?cites=14024850405532853821&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='PWbHESNHosIJ',
    scholar_ok=True,
    volume='7',
    summary="This approach aims to introduce Decision Provenance as a means to reach accountability in a highly interconnected context. It starts from the GDPR issues; but, from this concept, argues how it meets those ones.\n\nBy tieing accountability, from a legal point of view, to notions of responsibility, liability, and transparency (and transparency not necessarily meaning full transparency over the internal functions of a system, but information about the entities involved, the risks of using those systems and high-level information about what is happening with data or about what systems are doing), the authors point out the controllers/processors obligations to proactively, and by design and by default (Art. 12 and 25, Rec. 59 and 78), be able to demonstrate compliance with its various requirements, including the data processing principles (Art. 5), the data subject rights (especially Art. 17 and Art. 21, which follows that transparency over data; for example, data inventories that record where data came from, the subjects that it refers to, and where it goes to) also they are responsible for the accountability aspects in automated decision-making.\n\nFrom the above, given (i) the concerns around accountability for automated and algorithmic decision-making systems, (ii) the increasingly interconnected nature of system deployments, and (iii) the potential of provenance methods in this space, we propose decision provenance as a way forward; this approach introduces the decision provenance, which involves providing the information on the nature and contexts of the data flows and interconnections leading up to a decision or action, the flow-on effects, and also how such information can be leveraged for better system design,\ninspection, validation and operational (run-time) behaviour.\n\nFurther, the paper presents through many examples how this approach should be useful to ensure accountability in this context, and indicates some areas for implementing mechanisms (i.e., recording, management) and making data provenance meaningful for enabling its interpretation. But, in general, the approach is too vague and do not present a practical solution. Instead, this approach open issues for new discussions about the introduced concept.",
    related="propose DecisionProvenance, \"it proposes the idea of capturing and using the provenance of the decisions taken through the transitions of different systems in order to provide visibility over the relations and dependencies of interconnected systems where such visibility may not otherwise exist.\";\n\naimsTo \"assist ensuring the accountability challenges relating to the broader systems context (systems that are increasingly interconnected)\";\n\nscope gdprtext#:ControllerAccountability, gdprtext:Accountability\n\n",
    start_set=True,
    provenance_related=True,
))

ujcich2018a = DB(Work(
    2018, "A provenance model for the European union general data protection regulation",
    due="This paper present a data provenance model that aims to support legal reasoning and compliance checking. Additionally, this approach represents the data lifecycle, processing, legal base for a process.",
    display="Ujcich et al. Model 3",
    authors="Ujcich, Benjamin E and Bates, Adam and Sanders, William H",
    place=IPAW,
    ID='ujcich2018provenance',
    category='ok',
    cluster_id='4068207568007502254',
    entrytype='inproceedings',
    link='https://par.nsf.gov/servlets/purl/10087201',
    organization='Springer',
    pp='45--57',
    scholar='https://scholar.google.com.br/scholar?cites=4068207568007502254&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='rpmkkzotdTgJ',
    scholar_ok=True,
    summary='Based on a set of rights and obligations the authors have identified, it is proposed a data provenance model for representing GDPR concepts and activities related to the GDPR. This approach extends PROV concepts by proposing a set of classes and relations. The use of the approach takes place in three use cases based on a retail shop. The auors identifies some vunerabiities such approach might be subjected.',
    start_set=True,
))

ujcich2018b = DB(Work(
    2018, "Cross-app poisoning in software-defined networking",
    due="unrelated to GDPR",
    display="ujcich",
    authors="Ujcich, Benjamin E and Jero, Samuel and Edmundson, Anne and Wang, Qi and Skowyra, Richard and Landry, James and Bates, Adam and Sanders, William H and Nita-Rotaru, Cristina and Okhravi, Hamed",
    place=CCS,
    ID='ujcich2018cross',
    category='unrelated',
    cluster_id='982394684382062562',
    entrytype='inproceedings',
    link='https://dl.acm.org/doi/pdf/10.1145/3243734.3243759',
    pp='648--663',
    scholar='https://scholar.google.com/scholar?cites=982394684382062562&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='4ifTr8Iqog0J',
    scholar_ok=True,
    forward_steps=1,
))

westphal2018a = DB(Work(
    2018, "SPIRIT: a semantic transparency and compliance stack",
    due="Unrelated to provenance",
    display="westphal",
    authors="Westphal, Patrick and Fernandez Garcia, Javier David and Kirrane, Sabrina and Lehmann, Jens",
    place=SEMANTiCS,
    ID='westphal2018spirit',
    category='unrelated',
    cluster_id='8910619303694550681',
    entrytype='inproceedings',
    link='https://epub.wu.ac.at/6491/1/SPIRIT.pdf',
    organization='CEUR Workshop Proceedings',
    scholar='https://scholar.google.com/scholar?cites=8910619303694550681&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='mcZz1QvhqHsJ',
    scholar_ok=True,
    backward_steps=1,
))
