# coding: utf-8
from datetime import datetime
from snowballing.models import *
from ..places import *

esteves2021a = DB(Work(
    2021, "ODRL Profile for Expressing Consent through Granular Access Control Policies in Solid",
    due="The approach a extensions to the Access Control Language (ACL) to express rights and more complex privacy expressions. Such extensions is based on concepts from Open Digital Rights Language (ODRL), which provide concepts for representing stataments about the usage of some content, and also from Data Privacy Vocabulary (DPV), which is a rich vocabulary with privacy terms.",
    display="esteves",
    authors="Esteves, Beatriz and Pandit, Harshvardhan J and Rodrı́guez-Doncel, V̧́tor",
    place=IEEEESSPW,
    ID='esteves2021odrl',
    category='unrelated',
    cluster_id='15246464161540978441',
    entrytype='inproceedings',
    link='http://www.tara.tcd.ie/bitstream/handle/2262/96757/ODRL_Consent_ACP_Solid_CONSENT_WS_2021_AAM.pdf?sequence=1&isAllowed=y',
    organization='IEEE',
    pp='298--306',
    scholar='https://scholar.google.com.br/scholar?cites=15246464161540978441&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='CbdfLWBSltMJ',
    scholar_ok=True,
))

filipczuk2021a = DB(Work(
    2021, "Consent mechanisms in privacy engineering",
    due="Unrelated to provenance",
    display="filipczuk",
    authors="Filipczuk, Dorota",
    place=Thesis,
    ID='filipczuk2021consent',
    category='unrelated',
    cluster_id='16503246320892567099',
    entrytype='phdthesis',
    link='https://eprints.soton.ac.uk/456829/',
    scholar='https://scholar.google.com.br/scholar?cites=16503246320892567099&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='O96SRRdPB-UJ',
    scholar_ok=True,
))

hasan2021a = DB(Work(
    2021, "CISMET: A Semantic Ontology Framework for Regulatory-Requirements-Compliant Information Systems Development and Its Application in the GDPR Case",
    due="File not found",
    display="hasan",
    authors="Hasan, M Mahmudul and Kousiouris, George and Anagnostopoulos, Dimosthenis and Stamati, Teta and Loucopoulos, Peri and Nikolaidou, Mara",
    place=IJSWIS,
    ID='hasan2021cismet',
    category='nofile',
    cluster_id='9310707458503851573',
    entrytype='article',
    link='https://www.igi-global.com/article/cismet/272532',
    number='1',
    organization='IGI Global',
    pp='1--24',
    scholar='https://scholar.google.com.br/scholar?cites=9310707458503851573&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='Nb6zbxpHNoEJ',
    scholar_ok=True,
    volume='17',
    start_set=True,
))

kurteva2021a = DB(Work(
    2021, "Implementing Informed Consent with Knowledge Graphs",
    due="Document not publicly available",
    display="kurteva",
    authors="Kurteva, Anelia",
    place=ESWC,
    ID='kurteva2021implementing',
    category='nofile',
    cluster_id='8037422846503159691',
    entrytype='inproceedings',
    link='https://www.researchgate.net/profile/Anelia-Kurteva/publication/355043419_Implementing_Informed_Consent_with_Knowledge_Graphs_ESWC21_PhD_Symposium/links/615ae618e7bb415a5d60fb1a/Implementing-Informed-Consent-with-Knowledge-Graphs-ESWC21-PhD-Symposium.pdf',
    organization='Springer',
    pp='155--164',
    scholar='https://scholar.google.com.br/scholar?cites=8037422846503159691&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='iwduq36pim8J',
    scholar_ok=True,
))

kurtheva2021a = DB(Work(
    2021, "Consent through the lens of semantics: State of the art survey and best practices",
    due="Unrelated to provenance. This paper presents an overview of the existing semantic approaches addressing consent and recommends implementing consent with semantic technologies.",
    display="kurteva",
    authors="Kurteva, Anelia and Chhetri, Tek Raj and Pandit, Harshvardhan J and Fensel, Anna",
    place=SemanticWeb,
    ID='kurteva2021consent',
    category='unrelated',
    cluster_id='3027628374649535429',
    entrytype='article',
    link='https://content.iospress.com/articles/semantic-web/sw210438',
    number='Preprint',
    organization='IOS Press',
    pp='1--27',
    scholar='https://scholar.google.com.br/scholar?cites=3027628374649535429&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='xfvgNvdLBCoJ',
    scholar_ok=True,
))

pereira2021a = DB(Work(
    2021, "Plataform to centrally Manage User Preferences",
    due="Unrelated to provenance",
    display="pereira",
    authors="Pereira, João Manuel Ferreira",
    place=Book,
    ID='pereira2021plataform',
    category='unrelated',
    cluster_id='16630636099400146082',
    entrytype='article',
    link='https://repositorio-aberto.up.pt/bitstream/10216/139251/2/526282.pdf',
    scholar='https://scholar.google.com/scholar?cites=16630636099400146082&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='opyIZWvjy-YJ',
    scholar_ok=True,
    backward_steps=1,
))

norval2021a = DB(Work(
    2021, "Towards an accountable Internet of Things: A call for reviewability",
    due="It is not a peer-reviewed article.",
    display="norval",
    authors="Norval, Chris and Cobbe, Jennifer and Singh, Jatinder",
    place=arXiv,
    ID='norval2021towards',
    category='unrelated',
    cluster_id='14615755964735351410',
    entrytype='article',
    link='https://arxiv.org/pdf/2102.08132',
    pdfpage='',
    scholar='https://scholar.google.com/scholar?cites=14615755964735351410&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='curYwZyY1coJ',
    scholar_ok=True,
    related='iot',
    forward_steps=1,
))

rahmouni2021a = DB(Work(
    2021, "An ontology-based compliance audit framework for medical data sharing across europe.",
    due="This paper does not propose a provenance model",
    display="rahmouni",
    authors="Rahmouni, Hanene Boussi and Munir, Kamran and Essefi, Intidhar and Mont, Marco Casassa and Solomonides, Tony",
    place=IAJIT,
    ID='rahmouni2021ontology',
    category='unrelated',
    cluster_id='15875455072347989218',
    entrytype='article',
    link='https://iajit.org/portal/PDF/Vol%2018,%20No.%202/18671.pdf',
    number='2',
    pp='158--169',
    scholar='https://scholar.google.com.br/scholar?cites=15875455072347989218&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='4qT5ykbyUNwJ',
    scholar_ok=True,
    volume='18',
    backward_steps=1,
))

saltarella2021a = DB(Work(
    2021, "Privacy Design Strategies and the GDPR: A Systematic Literature Review",
    due="This approach does not propose a provenance model, though it presents a useful literature review concerned privacy strategies addressing the GDPR.",
    display="saltarella",
    authors="Saltarella, Marco and Desolda, Giuseppe and Lanzilotti, Rosa",
    place=HCII,
    ID='saltarella2021privacy',
    category='unrelated',
    cluster_id='18186720156512423929',
    entrytype='inproceedings',
    link='https://drive.google.com/file/d/17cPfzLLqS6Wp_IPhJOanU3Oqtb8wG7Zs/view?usp=sharing',
    organization='Springer',
    pp='241--257',
    scholar='https://scholar.google.com.br/scholar?cites=18186720156512423929&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='-Q9c_p81ZPwJ',
    scholar_ok=True,
))
