# coding: utf-8
from datetime import datetime
from snowballing.models import *
from ..places import *

agarwal2020a = DB(Work(
    2020, "GDPR-inspired IoT Ontology enabling Semantic Interoperability, Federation of Deployments and Privacy-Preserving Applications",
    due="This paper is not peer-reviewed",
    display="agarwal",
    authors="Agarwal, Rachit and Elsaleh, Tarek and Tragos, Elias",
    place=arXiv,
    ID='agarwal2020gdpr',
    category='unrelated',
    cluster_id='6966634315383540663',
    entrytype='article',
    link='https://arxiv.org/pdf/2012.10314',
    scholar='https://scholar.google.com.br/scholar?cites=6966634315383540663&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='t4t7wP90rmAJ',
    scholar_ok=True,
    start_set=True,
))

# ahmed2020a = DB(Work(
#     2020, "GDPR compliant consent driven data protection in online social networks: A blockchain-based approach",
#     due="[toReview=True; Forward=1; Page=1]",
#     display="ahmed",
#     authors="Ahmed, Javed and Yildirim, Sule and Nowostaki, Mariusz and Ramachandra, Raghvendra and Elezaj, Ogerta and Abomohara, Mohamad",
#     place=arXiv,
#     ID='ahmed2020gdpr',
#     category='unrelated',
#     cluster_id='2912405031957850186',
#     entrytype='inproceedings',
#     link='https://blockhack.osive.com/_downloads/0dfb3e976fdcd7b80bdd6cdf6fb03787/50.pdf',
#     organization='IEEE',
#     pp='307--312',
#     scholar='https://scholar.google.com.br/scholar?cites=2912405031957850186&as_sdt=2005&sciodt=0,5&hl=en',
#     scholar_id='SmjoK_LwaigJ',
#     scholar_ok=True,
# ))

agarwal2020b = DB(Work(
    2020, "GDPR-inspired IoT Ontology enabling Semantic Interoperability, Federation of Deployments and Privacy-Preserving Applications",
    due="Not a peer-reviewed document",
    display="agarwal",
    authors="Agarwal, Rachit and Elsaleh, Tarek and Tragos, Elias",
    place=arXiv,
    ID='agarwal2020gdpr',
    category='unrelated',
    cluster_id='6966634315383540663',
    entrytype='article',
    link='https://arxiv.org/pdf/2012.10314',
    scholar='https://scholar.google.com.br/scholar?cites=6966634315383540663&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='t4t7wP90rmAJ',
    scholar_ok=True,
))

ahmed2020a = DB(Work(
    2020, "GDPR compliant consent driven data protection in online social networks: A blockchain-based approach",
    due="Unrelated to provenance",
    display="ahmed",
    authors="Ahmed, Javed and Yildirim, Sule and Nowostaki, Mariusz and Ramachandra, Raghvendra and Elezaj, Ogerta and Abomohara, Mohamad",
    place=ICICT,
    ID='ahmed2020gdpr',
    category='unrelated',
    cluster_id='2912405031957850186',
    entrytype='inproceedings',
    link='https://blockhack.osive.com/_downloads/0dfb3e976fdcd7b80bdd6cdf6fb03787/50.pdf',
    organization='IEEE',
    pp='307--312',
    scholar='https://scholar.google.com.br/scholar?cites=2912405031957850186&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='SmjoK_LwaigJ',
    scholar_ok=True,
))

campagna2020a = DB(Work(
    2020, "Achieving GDPR Compliance through Provenance: An Extended Model.",
    due="This contribution extends prior data provenance model in the literature by providing new concepts that capable this model to represent new requisites stipulated by GDPR",
    display="campagna",
    authors="Campagna, Daniel Prett and da Silva, Altigran Soares and Braganholo, Vanessa",
    place=SBBD,
    ID='campagna2020achieving',
    category='ok',
    cluster_id='15772782772141981403',
    entrytype='inproceedings',
    link='https://sbbd.org.br/2020/wp-content/uploads/sites/13/2020/09/Archieving-GDPR-ST1.pdf',
    pp='13--24',
    scholar='https://scholar.google.com.br/scholar?cites=15772782772141981403&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='237sDF0u5NoJ',
    scholar_ok=True,
    start_set=True,
))

cox2020a = DB(Work(
    2020, "Time Ontology in OWL",
    due="Unrelated to GDPR",
    display="cox",
    authors="Simon Cox, Chris Little",
    place=Web,
    ID='TimeOnto58:online',
    entrytype='misc',
    howpublished='https://www.w3.org/TR/owl-time/',
    month='3',
    category='unrelated',
    backward_steps=1,
))

dealmine2020a = DB(Work(
    2020, "Consent for targeted advertising: the case of Facebook",
    due="Document not publicly available",
    display="dealmine",
    authors="De, Sourya Joyee and Imine, Abdessamad",
    place=AISOCIETY,
    ID='de2020consent',
    category='unrelated',
    cluster_id='15496552120048064916',
    entrytype='article',
    link='https://link.springer.com/article/10.1007/s00146-020-00981-5',
    number='4',
    organization='Springer',
    pp='1055--1064',
    scholar='https://scholar.google.com.br/scholar?cites=15496552120048064916&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='lJnKhgzQDtcJ',
    scholar_ok=True,
    volume='35',
))

debruyne2020a = DB(Work(
    2020, "“Just-in-time” generation of datasets by considering structured representations of given consent for GDPR compliance",
    due="Although this paper meets the crucial steps for compliance privacy issues, it does not introduce a new provenance ontology or model; Nevertheless, it uses prior ontologies. Even though this paper might be helpful for future work that considers practical steps towards implementing these privacy issues as GDPR prescribe.",
    display="debruyne",
    authors="Debruyne, Christophe and Pandit, Harshvardhan J and Lewis, Dave and O’Sullivan, Declan",
    place=JURIX,
    ID='debruyne2020just',
    category='unrelated',
    cluster_id='5120053941215386375',
    entrytype='article',
    link='https://link.springer.com/article/10.1007/s10115-020-01468-x',
    number='9',
    organization='Springer',
    pp='3615--3640',
    scholar='https://scholar.google.com.br/scholar?cites=5120053941215386375&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='B1v7rO4VDkcJ',
    scholar_ok=True,
    volume='62',
    start_set=True,
))

# fernández2020a = DB(Work(
#     2020, "User consent modeling for ensuring transparency and compliance in smart cities",
#     due="[toReview=True; Forward=1; Page=1]",
#     display="fernández",
#     authors="Fernández, Javier D and Sabou, Marta and Kirrane, Sabrina and Kiesling, Elmar and Ekaputra, Fajar J and Azzam, Amr and Wenning, Rigo",
#     place=arXiv,
#     ID='fernandez2020user',
#     category='ok',
#     cluster_id='8561348657580329970',
#     entrytype='article',
#     link='https://epub.wu.ac.at/7436/1/Transparency_and_compliance_in_Smart_Cities%20%281%29.pdf',
#     number='4',
#     organization='Springer',
#     pp='465--486',
#     scholar='https://scholar.google.com.br/scholar?cites=8561348657580329970&as_sdt=2005&sciodt=0,5&hl=en',
#     scholar_id='8stXfT4F0HYJ',
#     scholar_ok=True,
#     volume='24',
# ))

ezennaya2020a = DB(Work(
    2020, "DELIVERABLE: D6. 9",
    due="This paper does not present a provenance model.",
    display="ezennaya",
    authors="Ezennaya-Gomez, Salatiel",
    place=TechReport,
    ID='ezennayadeliverable',
    category='unrelated',
    cluster_id='13698816542724749548',
    entrytype='article',
    link='https://www.amber-biometrics.eu/wp-content/uploads/2020/09/20200401-Deliverable-D6.9.pdf',
    scholar='https://scholar.google.com.br/scholar?cites=13698816542724749548&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='7Hha8BD5G74J',
    scholar_ok=True,
))

fernández2020a = DB(Work(
    2020, "User consent modeling for ensuring transparency and compliance in smart cities",
    due="This paper does not propose a provenance model",
    display="fernández",
    authors="Fernández, Javier D and Sabou, Marta and Kirrane, Sabrina and Kiesling, Elmar and Ekaputra, Fajar J and Azzam, Amr and Wenning, Rigo",
    place=PUC,
    ID='fernandez2020user',
    category='unrelated',
    cluster_id='8561348657580329970',
    entrytype='article',
    link='https://epub.wu.ac.at/7436/1/Transparency_and_compliance_in_Smart_Cities%20%281%29.pdf',
    number='4',
    organization='Springer',
    pp='465--486',
    scholar='https://scholar.google.com/scholar?cites=8561348657580329970&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='8stXfT4F0HYJ',
    scholar_ok=True,
    volume='24',
    backward_steps=1,
))

jesus2020a = DB(Work(
    2020, "Towards an accountable web of personal information: The web-of-receipts",
    due="Unrelated to provenance",
    display="jesus",
    authors="Jesus, Vitor",
    place=IEEEAccess,
    ID='jesus2020towards',
    category='unrelated',
    cluster_id='3802577357190318979',
    entrytype='article',
    link='https://ieeexplore.ieee.org/iel7/6287639/8948470/08974193.pdf',
    organization='IEEE',
    pp='25383--25394',
    scholar='https://scholar.google.com.br/scholar?cites=3802577357190318979&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='g8tFnvV3xTQJ',
    scholar_ok=True,
    volume='8',
))

lee2020a = DB(Work(
    2020, "Design of Selective User Consent Procedure for Personal Information Collection Compliant to GDPR in IoT Environment",
    due="It is not written in English or Portuguese",
    display="lee",
    authors="Lee, Yong and Kim, Hwa Jong and Lee, Goo Yeon",
    place=UnknownJournal,
    ID='lee2020design',
    category='lang',
    cluster_id='15533044858408877033',
    entrytype='article',
    link='http://journal.dcs.or.kr/xml/23210/23210.pdf',
    number='2',
    pp='429--437',
    scholar='https://scholar.google.com.br/scholar?cites=15533044858408877033&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='6TurSQB2kNcJ',
    scholar_ok=True,
    volume='21',
))

leone2020a = DB(Work(
    2020, "Taking stock of legal ontologies: a feature-based comparative analysis",
    due="Unrelated to provenance. This paper brings the state-of-the-art in legal ontologies. It analyses the approaches to assist those who needs to user it.",
    display="leone",
    authors="Leone, Valentina and Di Caro, Luigi and Villata, Serena",
    place=AIL,
    ID='leone2020taking',
    category='unrelated',
    cluster_id='18265698632234957573',
    entrytype='article',
    link='https://hal.archives-ouvertes.fr/hal-03065217/file/SurveyLegalOnto_AI_Law-HAL.pdf',
    number='2',
    organization='Springer',
    pp='207--235',
    scholar='https://scholar.google.com/scholar?cites=18265698632234957573&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='BfuzVCHMfP0J',
    scholar_ok=True,
    volume='28',
    backward_steps=1,
))

mahindrakar2020a = DB(Work(
    2020, "Automating GDPR compliance using policy integrated blockchain",
    due="Although this approach is laid under an ontology, this is not the main contrbution and probably can not contrute with our purposes",
    display="mahindrakar",
    authors="Mahindrakar, Abhishek and Joshi, Karuna Pande",
    place=BigDataSecurity,
    ID='mahindrakar2020automating',
    category='unrelated',
    cluster_id='12847353138229095953',
    entrytype='inproceedings',
    link='https://mdsoar.org/bitstream/handle/11603/22800/Mahindrakar_umbc_0434M_12233.pdf?sequence=1',
    organization='IEEE',
    pp='86--93',
    scholar='https://scholar.google.com.br/scholar?cites=12847353138229095953&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='ES4lbJz3SrIJ',
    scholar_ok=True,
    start_set=True,
))

pandit2020a = DB(Work(
    2020, "Representing Activities associated with Processing of Personal Data and Consent using Semantic Web for GDPR Compliance",
    due="Related to GDPR. [TODO] This thesis presents a large and useful review of the state of the art about approaches related to GDPR. Additionally, this Pandit's contribution includes:\n\n(1) 120 questions, encompassed into 15 use-cases, elaborated from 7 reliable resources, in addition to the text of GDPR, to assist the endeavor of achieving GDPR compliance; (1a) he also elicits assumptions and constraints associated to those questions (p. 110)\n\n(2) 3 ontologies for representing: (2a) the GDPR text into a glossary of GDPR compliance concepts as a linked data (GDPRtext); (2b) the provenance of activities associated with personal data and consent in ex-ante and ex-post phases (GDPRov); (2c) information regarding consent (GConsent).\n\n# The State of the Art\n\n## 3.2 APPROACHES FOR GDPR COMPLIANCE UTILISING SEMANTIC WEB\n\n1. SPECIAL (Scalable Policy-aware Linked Data Architecture For Privacy, Transparency and Compliance)\n\n2. SERAMIS\n\n3. Vos et al.\n\n4. CitySPIN\n\n5. MIREL\n\n6. DAPRECO\n\n7. BPR4GDPR\n\n8. Elluri et al.\n\n9. Ujcich et al\n\n10. Personal Information Controller Service (PICS)\n\n11. ADvoCATE\n\n12. Ontology by Geko & Tjoa\n\n## APPROACHES ADDRESSING GDPR COMPLIANCE\n\n13. Layered Privacy Language (LPL)\n\n14. Lodge et al.\n\n15. Consent and Data Management Model by Peras\n\n16. Tom et al.\n\n17. Coletti et al.\n\n18. Corrales et al.\n\n19. LUCE\n\n20. Decision Provenance by Singh et al.\n\n21. Sion et al.\n\n22. privacyTracker\n\n23. Metrics for Transparency by Spagnuelo et al.\n\n24. meta-model for PLA by Diamantopoulou et al.\n\n25. Robol et al.\n\n26. Basin et al.\n\n27. RestAssured\n\n28. OPERANDO\n\n29. My Health My Data (MHMD)\n\n## 3.4 APPROACHES INVOLVING PRIVACY POLICIES\n\n30. Usable Privacy Project\n\n31. Polisis and other approaches based on Usable Privacy Project\n\n32. PrivacyGuide\n\n## 3.5 APPROACHES RELATED TO CONSENT\n\n33. Grando et al.\n\n34. Consent Receipt Specification\n\n## 3.6 UPCOMING RESEARCH PROJECTS ADDRESSING GDPR\n\n35. PDP4E\n\n36. DEFeND\n\n37. PAPAYA\n\n38. SMOOTH\n\n39. SODA\n\n40. DECODE\n\n41. MOSAICrOWN\n\n42. PoSEID-on\n\n# Contribution\n\n",
    display="pandit [TODO DUE]",
    authors="PANDIT, HARSHVARDHAN JITENDRA",
    place=arXiv,
    ID='pandit2020representing',
    category='ok',
    cluster_id='7232081120271493220',
    entrytype='phdthesis',
    link='https://harshp.com/research/publications/035-representing-activities-processing-personal-data-consent-semweb-gdpr-compliance',
    scholar='https://scholar.google.com.br/scholar?cites=7232081120271493220&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='ZGiXMHaDXWQJ',
    scholar_ok=True,
    start_set=True,
))

pandit2020b = DB(Work(
    2020, "Standardisation, Data Interoperability, and GDPR",
    due="Although this paper argues in favor of approaching GDPR issues using semantic models (e.g., provenance models) to support further standardization efforts, it does not introduce these models. Instead, the authors are concerned with providing an overview of existing standards and their relevance to the ecosystem brought about by the GDPR.",
    display="pandit",
    authors="Pandit, Harshvardhan Jitendra and Debruyne, Christophe and O'Sullivan, Declan and Lewis, Dave",
    place=Book,
    ID='pandit2020standardisation',
    category='unrelated',
    cluster_id='2319798870600482401',
    entrytype='incollection',
    link='http://www.tara.tcd.ie/bitstream/handle/2262/91583/chapter.pdf?sequence=1',
    organization='IGI Global',
    pp='199--225',
    scholar='https://scholar.google.com/scholar?cites=2319798870600482401&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='YX5-MMiUMSAJ',
    scholar_ok=True,
    backward_steps=1,
))

riva2020a = DB(Work(
    2020, "SoK: Engineering privacy-aware high-tech systems",
    due="Related to GDPR, but not address a solution for a GDPR requirement. It's a mapping",
    display="riva",
    authors="Riva, Giovanni Maria and Vasenev, Alexandr and Zannone, Nicola",
    place=ARES,
    ID='riva2020sok',
    category='unrelated',
    cluster_id='10340662963669714270',
    entrytype='inproceedings',
    link='https://www.researchgate.net/profile/Nicola-Zannone/publication/343289494_SoK_Engineering_privacy-aware_high-tech_systems/links/5f496462458515a88b811fdf/SoK-Engineering-privacy-aware-high-tech-systems.pdf',
    pdfpage='',
    pp='1--10',
    scholar='https://scholar.google.com/scholar?cites=10340662963669714270&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='XkWSoy1qgY8J',
    scholar_ok=True,
    forward_steps=1,
))

ujcich2020a = DB(Work(
    2020, "Securing the software-defined networking control plane by using control and data dependency techniques",
    due="Not related to data provenance.",
    display="ujcich",
    authors="Ujcich, Benjamin E",
    place=Thesis,
    ID='ujcich2020securing',
    category='unrelated',
    cluster_id='7364673729312880224',
    entrytype='phdthesis',
    link='https://www.ideals.illinois.edu/bitstream/handle/2142/108612/UJCICH-DISSERTATION-2020.pdf?sequence=1',
    pdfpage='',
    scholar='https://scholar.google.com/scholar?cites=7364673729312880224&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='YHZYsryTNGYJ',
    scholar_ok=True,
    forward_steps=1,
))

이용2020a = DB(Work(
    2020, "IoT 환경에서 GDPR 에 부합하는 선택적 개인정보 동의획득 절차 설계",
    due="This document is not published in english",
    display="이용",
    authors="이용 and 김화종 and 이구연",
    place=Web,
    ID='이용2020iot',
    category='lang',
    cluster_id='11592367261078715324',
    entrytype='article',
    link='https://www.dbpia.co.kr/Journal/articleDetail?nodeId=NODE09309879',
    number='2',
    pp='429--437',
    scholar='https://scholar.google.com.br/scholar?cites=11592367261078715324&as_sdt=2005&sciodt=0,5&hl=en',
    scholar_id='vPt23ppc4KAJ',
    scholar_ok=True,
    volume='21',
    forward_steps=1,
))
